Repository woowacourse-teams/2022-pickpick, pull requests merged in 2022-10, with the labels that each got.

#563 refactor: Exception 내부에 ErrorCode 필드가 빠진 것 수정
  backend/src/main/java/com/pickpick/exception/BadRequestException.java
  backend/src/main/java/com/pickpick/exception/NotFoundException.java
  backend/src/main/java/com/pickpick/exception/auth/ExpiredTokenException.java
  backend/src/main/java/com/pickpick/exception/auth/InvalidTokenException.java
  backend/src/main/java/com/pickpick/exception/channel/ChannelInvalidNameException.java
  backend/src/main/java/com/pickpick/exception/channel/ChannelNotFoundException.java
  backend/src/main/java/com/pickpick/exception/channel/SubscriptionDuplicateException.java
  backend/src/main/java/com/pickpick/exception/channel/SubscriptionInvalidOrderException.java
  backend/src/main/java/com/pickpick/exception/channel/SubscriptionNotExistException.java
  backend/src/main/java/com/pickpick/exception/channel/SubscriptionNotFoundException.java
  backend/src/main/java/com/pickpick/exception/channel/SubscriptionOrderDuplicateException.java
  backend/src/main/java/com/pickpick/exception/member/MemberInvalidThumbnailUrlException.java
  backend/src/main/java/com/pickpick/exception/member/MemberInvalidUsernameException.java
  backend/src/main/java/com/pickpick/exception/member/MemberNotFoundException.java
  backend/src/main/java/com/pickpick/exception/message/BookmarkDeleteFailureException.java
  backend/src/main/java/com/pickpick/exception/message/BookmarkNotFoundException.java
  backend/src/main/java/com/pickpick/exception/message/MessageNotFoundException.java
  backend/src/main/java/com/pickpick/exception/message/ReminderDeleteFailureException.java
  backend/src/main/java/com/pickpick/exception/message/ReminderNotFoundException.java
  backend/src/main/java/com/pickpick/exception/message/ReminderUpdateFailureException.java
  backend/src/main/java/com/pickpick/exception/slackevent/SlackEventNotFoundException.java
  backend/src/main/java/com/pickpick/exception/slackevent/SlackEventServiceNotFoundException.java
  backend/src/main/java/com/pickpick/exception/utils/InvalidJsonRequestException.java
Labels: 🎉 BE, ⚙️ REFACTOR

#558 test: 인수 테스트 코드 구조 변경 및 인증인가 인수테스트 리팩터링
  backend/src/test/java/com/pickpick/acceptance/AcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/RestHandler.java
  backend/src/test/java/com/pickpick/acceptance/auth/AuthAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/auth/AuthRestHandler.java
  backend/src/test/java/com/pickpick/acceptance/channel/ChannelAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/channel/ChannelSubscriptionAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/member/MemberAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/BookmarkAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/MessageAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/MemberEventAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/MessageEventAcceptanceTest.java
  backend/src/test/resources/application.yml
Labels: 🎉 BE, ⚙️ REFACTOR, 💯 TEST

#555 refactor: 채널 도메인(슬랙 이벤트 포함) 관련 서비스 테스트 리팩토링
  backend/src/test/java/com/pickpick/channel/application/ChannelServiceTest.java
  backend/src/test/java/com/pickpick/channel/application/ChannelSubscriptionServiceTest.java
  backend/src/test/java/com/pickpick/fixture/ChannelFixture.java
  backend/src/test/java/com/pickpick/slackevent/application/channel/ChannelDeletedServiceTest.java
Labels: 🎉 BE, ⚙️ REFACTOR, 💯 TEST

#567 refactor: 외부 라이브러리의 로직 추상화
  backend/src/main/java/com/pickpick/auth/application/AuthService.java
  backend/src/main/java/com/pickpick/channel/application/ChannelCreateService.java
  backend/src/main/java/com/pickpick/exception/SlackApiCallException.java
  backend/src/main/java/com/pickpick/member/application/MemberInitializer.java
  backend/src/main/java/com/pickpick/message/application/ReminderSender.java
  backend/src/main/java/com/pickpick/support/SlackClient.java
  backend/src/test/java/com/pickpick/acceptance/auth/AuthAcceptanceTest.java
  backend/src/test/java/com/pickpick/auth/application/AuthServiceTest.java
  backend/src/test/java/com/pickpick/channel/application/ChannelCreateServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageCreatedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageFileShareServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastServiceTest.java
Labels: 🎉 BE, ⚙️ REFACTOR

#569 refactor: Repository 인터페이스 내부에 예외를 던지는 default 메서드 추가
  backend/src/main/java/com/pickpick/auth/application/AuthService.java
  backend/src/main/java/com/pickpick/channel/application/ChannelSubscriptionService.java
  backend/src/main/java/com/pickpick/channel/domain/ChannelRepository.java
  backend/src/main/java/com/pickpick/channel/domain/ChannelSubscriptionRepository.java
  backend/src/main/java/com/pickpick/member/domain/MemberRepository.java
  backend/src/main/java/com/pickpick/message/application/BookmarkService.java
  backend/src/main/java/com/pickpick/message/application/MessageService.java
  backend/src/main/java/com/pickpick/message/application/ReminderService.java
  backend/src/main/java/com/pickpick/message/domain/BookmarkRepository.java
  backend/src/main/java/com/pickpick/message/domain/MessageRepository.java
  backend/src/main/java/com/pickpick/message/domain/ReminderRepository.java
  backend/src/main/java/com/pickpick/slackevent/application/channel/ChannelRenameService.java
  backend/src/main/java/com/pickpick/slackevent/application/member/MemberChangedService.java
  backend/src/main/java/com/pickpick/slackevent/application/message/MessageChangedService.java
  backend/src/main/java/com/pickpick/slackevent/application/message/MessageCreatedService.java
  backend/src/main/java/com/pickpick/slackevent/application/message/MessageFileShareService.java
  backend/src/main/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastService.java
Labels: 🎉 BE, ⚙️ REFACTOR

#559 refactor: 슬랙 이벤트 중 멤버 관련 테스트 리팩토링
  backend/src/test/java/com/pickpick/fixture/MemberFixture.java
  backend/src/test/java/com/pickpick/slackevent/application/member/MemberChangedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/member/MemberJoinServiceTest.java
Labels: 🎉 BE, ⚙️ REFACTOR, 💯 TEST

#568 feat: 북마크 정렬 기준 변경 및 서비스 테스트 리팩터링
  backend/src/main/java/com/pickpick/PickpickApplication.java
  backend/src/main/java/com/pickpick/message/application/BookmarkService.java
  backend/src/main/java/com/pickpick/message/domain/Bookmark.java
  backend/src/test/java/com/pickpick/acceptance/message/BookmarkAcceptanceTest.java
  backend/src/test/java/com/pickpick/fixture/BookmarkFindRequestFactory.java
  backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
  backend/src/test/resources/bookmark.sql
  backend/src/test/resources/message.sql
Labels: 🎉 BE, ⚙️ REFACTOR

#573 feat: RestDocs 에 에러코드 추가
  backend/src/docs/asciidoc/index.adoc
  backend/src/test/java/com/pickpick/support/DocsControllerTest.java
  backend/src/test/java/com/pickpick/support/ErrorCodeController.java
  backend/src/test/java/com/pickpick/support/ErrorCodeDocsTest.java
  backend/src/test/java/com/pickpick/support/ErrorCodeSnippet.java
  backend/src/test/resources/org/springframework/restdocs/templates/error-code-template.snippet
Labels: 🎉 BE, ✨ FEAT, 📝 DOCS

#576 refactor: Modal component 생성 및 중복되는 컴포넌트 제거
  frontend/src/components/@layouts/Navigation/index.tsx
  frontend/src/components/@shared/Modal/index.tsx
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/Reminder/index.tsx
  frontend/src/pages/SearchResult/index.tsx
  frontend/src/pages/SpecificDateFeed/index.tsx
Labels: 🎁 FE, ⚙️ REFACTOR

#577 refactor: ReminderModal 네이밍 변경 -> AddReminder
  frontend/src/components/@shared/Dropdown/@hooks/useDropdown.ts
  frontend/src/components/@shared/Dropdown/index.tsx
  frontend/src/components/AddReminder/@hooks/useDatePicker.ts
  frontend/src/components/AddReminder/@hooks/useTimePicker.ts
  frontend/src/components/AddReminder/@utils/index.ts
  frontend/src/components/AddReminder/DateTimePicker/DatePicker/index.tsx
  frontend/src/components/AddReminder/DateTimePicker/DatePicker/style.ts
  frontend/src/components/AddReminder/DateTimePicker/DateTimePickerOptions/index.tsx
  frontend/src/components/AddReminder/DateTimePicker/DateTimePickerOptions/style.ts
  frontend/src/components/AddReminder/DateTimePicker/DateTimePickerToggle/index.tsx
  frontend/src/components/AddReminder/DateTimePicker/DateTimePickerToggle/style.ts
  frontend/src/components/AddReminder/DateTimePicker/TimePicker/index.tsx
  frontend/src/components/AddReminder/index.tsx
  frontend/src/components/AddReminder/style.ts
  frontend/src/components/DateDropdown/index.tsx
  frontend/src/components/SearchForm/index.tsx
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/Reminder/index.tsx
  frontend/src/pages/SearchResult/index.tsx
  frontend/src/pages/SpecificDateFeed/index.tsx
Labels: 🎁 FE, ⚙️ REFACTOR

#579 refactor: hooks 폴더 구조 수정
  frontend/src/components/@layouts/Navigation/index.tsx
  frontend/src/components/@shared/Dropdown/index.tsx
  frontend/src/components/AddReminder/@hooks/useDatePicker.ts
  frontend/src/components/AddReminder/@hooks/useTimePicker.ts
  frontend/src/components/AddReminder/index.tsx
  frontend/src/components/EmptyStatus/index.tsx
  frontend/src/components/SearchForm/@hooks/useSelectChannels.ts
  frontend/src/hooks/@query/useGetCertification.ts
  frontend/src/hooks/@query/useGetChannels.ts
  frontend/src/hooks/@query/useGetInfiniteBookmarks.ts
  frontend/src/hooks/@query/useGetInfiniteMessages.ts
  frontend/src/hooks/@query/useGetInfiniteReminders.ts
  frontend/src/hooks/@query/useGetSubscribedChannels.ts
  frontend/src/hooks/@query/useMutateBookmark.ts
  frontend/src/hooks/@query/useMutateChannels.ts
  frontend/src/hooks/@query/useMutateReminder.ts
  frontend/src/hooks/@shared/useGetSearchParam.ts
  frontend/src/hooks/@shared/useInput.ts
  frontend/src/hooks/@shared/useModal.ts
  frontend/src/hooks/@shared/useOuterClick.ts
  frontend/src/hooks/@shared/usePushPreviousPage.ts
  frontend/src/hooks/@shared/useScrollToTop.ts
  frontend/src/hooks/@shared/useWebStorage.ts
  frontend/src/hooks/useModeTheme.ts
  frontend/src/hooks/useRecentFeedPath.ts
  frontend/src/pages/AddChannel/index.tsx
  frontend/src/pages/Bookmark/index.tsx
  frontend/src/pages/Certification/index.tsx
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/Reminder/index.tsx
  frontend/src/pages/SearchResult/index.tsx
  frontend/src/pages/SpecificDateFeed/index.tsx
Labels: 🎁 FE, ⚙️ REFACTOR

#570 refactor: 컨트롤러 테스트를 WebMvcTest로 개선
  backend/src/docs/asciidoc/index.adoc
  backend/src/test/java/com/pickpick/channel/ui/ChannelControllerTest.java
  backend/src/test/java/com/pickpick/channel/ui/ChannelSubscriptionControllerTest.java
  backend/src/test/java/com/pickpick/message/ui/BookmarkControllerTest.java
  backend/src/test/java/com/pickpick/message/ui/MessageControllerTest.java
  backend/src/test/java/com/pickpick/message/ui/ReminderControllerTest.java
  backend/src/test/java/com/pickpick/support/DocsControllerTest.java
  backend/src/test/java/com/pickpick/support/ErrorCodeController.java
  backend/src/test/java/com/pickpick/support/ErrorCodeDocsTest.java
  backend/src/test/java/com/pickpick/support/ErrorCodeSnippet.java
  backend/src/test/java/com/pickpick/support/RestDocsTestSupport.java
  backend/src/test/resources/org/springframework/restdocs/templates/error-code-template.snippet
Labels: 🎉 BE, ⚙️ REFACTOR, 💯 TEST

#571 refactor: 채널 인수 테스트 개선 및 SlackClient 분리
  backend/src/main/java/com/pickpick/auth/application/AuthService.java
  backend/src/main/java/com/pickpick/channel/application/ChannelCreateService.java
  backend/src/main/java/com/pickpick/member/application/MemberInitializer.java
  backend/src/main/java/com/pickpick/message/application/ReminderSender.java
  backend/src/main/java/com/pickpick/support/ExternalClient.java
  backend/src/main/java/com/pickpick/support/SlackClient.java
  backend/src/test/java/com/pickpick/acceptance/AcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/RestHandler.java
  backend/src/test/java/com/pickpick/acceptance/auth/AuthAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/auth/AuthRestHandler.java
  backend/src/test/java/com/pickpick/acceptance/channel/ChannelAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/channel/ChannelRestHandler.java
  backend/src/test/java/com/pickpick/acceptance/channel/ChannelSubscriptionAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/SlackEventRestHandler.java
  backend/src/test/java/com/pickpick/fixture/ChannelFixture.java
  backend/src/test/java/com/pickpick/support/FakeClient.java
  backend/src/test/java/com/pickpick/support/TestConfig.java
Labels: 🎉 BE, ⚙️ REFACTOR, 💯 TEST

#583 docs: 리드미 업데이트
  README.md
Labels: 🌈 ALL, 📝 DOCS

#585 fix: 잘못 표기된 DisplayName과 메서드명 정정
  backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
Labels: 🎉 BE, 🛠 FIX, 💯 TEST

#584 test: 슬랙 이벤트 인수 테스트 개선
  backend/src/test/java/com/pickpick/acceptance/member/MemberAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/MemberEventAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/MessageEventAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/SlackEventRequestFactory.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/SlackEventRestHandler.java
  backend/src/test/java/com/pickpick/fixture/ChannelFixture.java
Labels: 🎉 BE, ⚙️ REFACTOR, 💯 TEST

#592 refactor: 타입스크립 1차 리팩터링
  frontend/src/@types/api.ts
  frontend/src/@types/shared.ts
  frontend/src/@types/utils.ts
  frontend/src/@utils/index.ts
  frontend/src/api/auth.ts
  frontend/src/api/bookmarks.ts
  frontend/src/api/channels.ts
  frontend/src/api/messages.ts
  frontend/src/api/reminders.ts
  frontend/src/components/@layouts/LayoutContainer/index.tsx
  frontend/src/components/@layouts/Navigation/index.tsx
  frontend/src/components/@shared/Button/index.tsx
  frontend/src/components/@shared/Dropdown/index.tsx
  frontend/src/components/@shared/IconButton/index.tsx
  frontend/src/components/@shared/InfiniteScroll/index.tsx
  frontend/src/components/@shared/Modal/index.tsx
  frontend/src/components/@shared/Portal/index.tsx
  frontend/src/components/@shared/WrapperButton/index.tsx
  frontend/src/components/@shared/WrapperNavLink/index.tsx
  frontend/src/components/@shared/WrapperNavLink/style.ts
  frontend/src/components/AddReminder/@hooks/useTimePicker.ts
  frontend/src/components/AddReminder/@utils/index.ts
  frontend/src/components/AddReminder/DateTimePicker/DateTimePickerToggle/index.tsx
  frontend/src/components/ChannelsDrawer/index.tsx
  frontend/src/components/ErrorBoundary/index.tsx
  frontend/src/components/MessageCard/index.tsx
  frontend/src/components/Router/PublicRouter/index.tsx
  frontend/src/components/SearchForm/@hooks/useSelectChannels.ts
  frontend/src/components/SearchForm/SearchInput/index.tsx
  frontend/src/components/SearchForm/SearchOptions/index.tsx
  frontend/src/hooks/@query/useGetCertification.ts
  frontend/src/hooks/@query/useGetChannels.ts
  frontend/src/hooks/@query/useGetInfiniteBookmarks.ts
  frontend/src/hooks/@query/useGetInfiniteMessages.ts
  frontend/src/hooks/@query/useGetInfiniteReminders.ts
  frontend/src/hooks/@query/useGetSubscribedChannels.ts
  frontend/src/hooks/@query/useMutateBookmark.ts
  frontend/src/hooks/@query/useMutateChannels.ts
  frontend/src/hooks/@query/useMutateReminder.ts
  frontend/src/hooks/@shared/useGetSearchParam.ts
  frontend/src/hooks/@shared/useInput.ts
  frontend/src/hooks/@shared/useModal.ts
  frontend/src/hooks/@shared/useOuterClick.ts
  frontend/src/hooks/@shared/usePushPreviousPage.ts
  frontend/src/hooks/@shared/useScrollToTop.ts
  frontend/src/hooks/@shared/useWebStorage.ts
  frontend/src/hooks/useApiError.ts
  frontend/src/hooks/useAuthentication.ts
  frontend/src/hooks/useMessageDate.ts
  frontend/src/hooks/useModeTheme.ts
  frontend/src/hooks/useRecentFeedPath.ts
  frontend/src/hooks/useSetReminderTargetMessage.ts
  frontend/src/hooks/useSnackbar.ts
  frontend/src/hooks/useTopScreenEventHandlers.ts
  frontend/src/pages/Bookmark/index.tsx
  frontend/src/pages/Certification/index.tsx
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/Reminder/index.tsx
  frontend/src/pages/SearchResult/index.tsx
  frontend/src/pages/SpecificDateFeed/index.tsx
Labels: 🎁 FE, ⚙️ REFACTOR

#593 test: 메시지 인수 테스트 개선
  backend/src/test/java/com/pickpick/acceptance/AcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/RestHandler.java
  backend/src/test/java/com/pickpick/acceptance/channel/ChannelRestHandler.java
  backend/src/test/java/com/pickpick/acceptance/channel/ChannelSubscriptionAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/BookmarkAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/BookmarkRestHandler.java
  backend/src/test/java/com/pickpick/acceptance/message/MessageAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/MessageRestHandler.java
  backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/ReminderRestHandler.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/SlackEventRequestFactory.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/SlackEventRestHandler.java
Labels: 🎉 BE, ⚙️ REFACTOR, 💯 TEST

#598 refactor: code smell 최소화
  backend/src/main/java/com/pickpick/auth/support/AuthorizationExtractor.java
  backend/src/main/java/com/pickpick/exception/auth/ExtractTokenFailException.java
  backend/src/test/java/com/pickpick/acceptance/AcceptanceTestBase.java
  backend/src/test/java/com/pickpick/acceptance/auth/AuthAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/channel/ChannelAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/channel/ChannelSubscriptionAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/BookmarkAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/MessageAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/MemberEventAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/MessageEventAcceptanceTest.java
  backend/src/test/java/com/pickpick/channel/ui/ChannelControllerTest.java
  backend/src/test/java/com/pickpick/channel/ui/ChannelSubscriptionControllerTest.java
  backend/src/test/java/com/pickpick/message/ui/BookmarkControllerTest.java
  backend/src/test/java/com/pickpick/message/ui/MessageControllerTest.java
  backend/src/test/java/com/pickpick/message/ui/ReminderControllerTest.java
  backend/src/test/java/com/pickpick/support/DocsControllerTestBase.java
  backend/src/test/java/com/pickpick/support/ErrorCodeDocsTest.java
Labels: 🎉 BE, ⚙️ REFACTOR

#596 feat: 채널 목록 조회 API 변경
  backend/src/main/java/com/pickpick/auth/application/AuthService.java
  backend/src/main/java/com/pickpick/channel/application/ChannelService.java
  backend/src/main/java/com/pickpick/exception/member/MemberTokenNotFoundException.java
  backend/src/main/java/com/pickpick/member/domain/Member.java
  backend/src/main/java/com/pickpick/slackevent/domain/Participation.java
  backend/src/main/java/com/pickpick/support/ExternalClient.java
  backend/src/main/java/com/pickpick/support/SlackClient.java
  backend/src/test/java/com/pickpick/acceptance/auth/AuthAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/channel/ChannelAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/channel/ChannelSubscriptionAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/BookmarkAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/MessageAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java
  backend/src/test/java/com/pickpick/channel/application/ChannelServiceTest.java
  backend/src/test/java/com/pickpick/fixture/ChannelFixture.java
  backend/src/test/java/com/pickpick/fixture/MemberFixture.java
  backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
  backend/src/test/java/com/pickpick/support/FakeClient.java
Labels: 🎉 BE, ✨ FEAT

#604 fix: 토큰 타입 varchar(64) -> varchar(256) 로 수정
  backend/src/main/java/com/pickpick/member/domain/Member.java
  backend/src/main/java/com/pickpick/workspace/domain/Workspace.java
Labels: 🐛 BUG, 🎉 BE, 🛠 FIX

#597 feat: 채널 생성 API 구현
  backend/src/main/java/com/pickpick/auth/application/AuthService.java
  backend/src/main/java/com/pickpick/channel/application/ChannelService.java
  backend/src/main/java/com/pickpick/slackevent/application/SlackEvent.java
  backend/src/main/java/com/pickpick/slackevent/application/channel/ChannelCreatedService.java
  backend/src/main/java/com/pickpick/slackevent/application/channel/ChannelRenameService.java
  backend/src/main/java/com/pickpick/slackevent/application/channel/dto/ChannelRenameDto.java
  backend/src/main/java/com/pickpick/slackevent/application/channel/dto/ChannelRenameRequest.java
  backend/src/main/java/com/pickpick/slackevent/application/channel/dto/ChannelRequest.java
  backend/src/main/java/com/pickpick/support/ExternalClient.java
  backend/src/main/java/com/pickpick/support/SlackClient.java
  backend/src/test/java/com/pickpick/acceptance/channel/ChannelAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/ChannelEventAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/MemberEventAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/MessageEventAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/SlackEventRequestFactory.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/SlackEventRestHandler.java
  backend/src/test/java/com/pickpick/auth/application/AuthServiceTest.java
  backend/src/test/java/com/pickpick/channel/application/ChannelServiceTest.java
  backend/src/test/java/com/pickpick/fixture/ChannelFixture.java
  backend/src/test/java/com/pickpick/fixture/WorkspaceFixture.java
  backend/src/test/java/com/pickpick/slackevent/SlackEventTest.java
  backend/src/test/java/com/pickpick/slackevent/application/channel/ChannelCreatedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/member/MemberJoinServiceTest.java
  backend/src/test/java/com/pickpick/support/FakeClient.java
Labels: 🎉 BE, ✨ FEAT

#605 feat: 채널 구독 시 Bot 초대 기능 추가
  backend/src/main/java/com/pickpick/auth/application/dto/BotInfoDto.java
  backend/src/main/java/com/pickpick/channel/application/ChannelSubscriptionService.java
  backend/src/main/java/com/pickpick/support/ExternalClient.java
  backend/src/main/java/com/pickpick/support/SlackClient.java
  backend/src/main/java/com/pickpick/workspace/domain/Workspace.java
  backend/src/test/java/com/pickpick/auth/application/AuthServiceTest.java
  backend/src/test/java/com/pickpick/channel/application/ChannelSubscriptionServiceTest.java
  backend/src/test/java/com/pickpick/fixture/WorkspaceFixture.java
  backend/src/test/java/com/pickpick/support/FakeClient.java
Labels: 🎉 BE, ✨ FEAT

#600 refactor: 리마인더 서비스 테스트 리팩터링
  backend/src/test/java/com/pickpick/fixture/ReminderFindRequestFactory.java
  backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java
Labels: 🎉 BE, ⚙️ REFACTOR, 💯 TEST

#609 refactor: BotInfoDto의 이름을 WorkspaceInfoDto로 변경
  backend/src/main/java/com/pickpick/auth/application/AuthService.java
  backend/src/main/java/com/pickpick/auth/application/dto/WorkspaceInfoDto.java
  backend/src/main/java/com/pickpick/support/ExternalClient.java
  backend/src/main/java/com/pickpick/support/SlackClient.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/ChannelEventAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/MemberEventAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/MessageEventAcceptanceTest.java
  backend/src/test/java/com/pickpick/support/FakeClient.java
Labels: 🎉 BE, ⚙️ REFACTOR

#610 refactor: 모든 sql 파일 제거
  backend/src/test/resources/bookmark.sql
  backend/src/test/resources/channel-subscription.sql
  backend/src/test/resources/channel.sql
  backend/src/test/resources/member.sql
  backend/src/test/resources/message.sql
  backend/src/test/resources/reminder.sql
  backend/src/test/resources/truncate.sql
Labels: 🎉 BE, ⚙️ REFACTOR, 💯 TEST

#614 워크스페이스 개인화 작업 이후 서비스 테스트 코드 내부에서 workspace 사용하도록 수정
  backend/src/main/java/com/pickpick/auth/application/AuthService.java
  backend/src/test/java/com/pickpick/auth/application/AuthServiceTest.java
  backend/src/test/java/com/pickpick/channel/application/ChannelServiceTest.java
  backend/src/test/java/com/pickpick/channel/application/ChannelSubscriptionServiceTest.java
  backend/src/test/java/com/pickpick/channel/domain/ChannelSubscriptionTest.java
  backend/src/test/java/com/pickpick/channel/domain/ChannelTest.java
  backend/src/test/java/com/pickpick/fixture/ChannelFixture.java
  backend/src/test/java/com/pickpick/fixture/MemberFixture.java
  backend/src/test/java/com/pickpick/member/domain/MemberTest.java
  backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
  backend/src/test/java/com/pickpick/message/application/MessageServiceTest.java
  backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/channel/ChannelCreatedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/channel/ChannelDeletedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/channel/ChannelRenameServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/member/MemberChangedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/member/MemberJoinServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageChangedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageCreatedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageDeletedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageFileShareServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastServiceTest.java
  backend/src/test/java/com/pickpick/support/FakeClient.java
Labels: 🎉 BE, ⚙️ REFACTOR, 💯 TEST

#615 refactor: 스낵바 컴포넌트 리팩터링 및 UI 개선
  frontend/src/@styles/colors.ts
  frontend/src/@styles/theme.ts
  frontend/src/@types/shared.ts
  frontend/src/components/@shared/IconButton/style.ts
  frontend/src/components/Calendar/index.tsx
  frontend/src/components/Calendar/style.ts
  frontend/src/components/Snackbar/index.tsx
  frontend/src/components/Snackbar/style.ts
Labels: 🎁 FE, ⚙️ REFACTOR

#616 refactor: useModal 커스텀 훅 리팩터링
  frontend/src/components/@layouts/Navigation/index.tsx
  frontend/src/hooks/@shared/useModal.ts
Labels: 🎁 FE, ⚙️ REFACTOR

#617 feat: 슬랙 워크스페이스 등록 기능
  frontend/.env.development
  frontend/src/@constants/api.ts
  frontend/src/@constants/path.ts
  frontend/src/Routes.tsx
  frontend/src/api/auth.ts
  frontend/src/components/@layouts/Header/index.tsx
  frontend/src/components/@shared/Button/index.tsx
  frontend/src/components/@shared/Button/style.ts
  frontend/src/components/SearchForm/SearchOptions/index.tsx
  frontend/src/hooks/@query/useGetRegisterSlackWorkspace.ts
  frontend/src/pages/AddChannel/index.tsx
  frontend/src/pages/Home/index.tsx
  frontend/src/pages/RegisterSlackWorkspace/index.tsx
  frontend/src/pages/index.tsx
  frontend/webpack.dev.js
  frontend/webpack.prod.js
Labels: 🎁 FE, ✨ FEAT

#622 refactor: font 설정 변경
  frontend/public/index.html
  frontend/src/@styles/GlobalStyle.ts
Labels: 🎁 FE, ⚙️ REFACTOR

#623 hotfix: axios baseURL 수정
  frontend/src/api/index.ts
Labels: 🎁 FE, 🚨 HOTFIX

#626 feat: 로깅 처리 추가
  backend/src/main/java/com/pickpick/slackevent/ui/SlackEventController.java
  backend/src/main/java/com/pickpick/support/LoggingAspect.java
  backend/src/main/resources/appenders/async-console-appender.xml
  backend/src/main/resources/appenders/async-file-appender-info.xml
  backend/src/main/resources/logback-spring.xml
Labels: 🎉 BE, ✨ FEAT

#630 refactor: 웹 접근성 적용 (1차)
  frontend/src/@styles/shared.ts
  frontend/src/api/index.ts
  frontend/src/components/Calendar/index.tsx
  frontend/src/components/Calendar/style.ts
  frontend/src/components/DateDropdown/DateDropdownMenu/index.tsx
  frontend/src/components/DateDropdown/DateDropdownOption/index.tsx
  frontend/src/components/DateDropdown/index.tsx
  frontend/src/components/DateDropdown/style.ts
  frontend/src/components/EmptyStatus/index.tsx
  frontend/src/components/EmptyStatus/style.ts
  frontend/src/components/MessageCard/MessageCardSkeleton/index.tsx
  frontend/src/components/MessageCard/MessageIconButtons/BookmarkButton/index.tsx
  frontend/src/components/MessageCard/MessageIconButtons/ReminderButton/index.tsx
  frontend/src/components/MessageCard/index.tsx
  frontend/src/components/MessageCard/style.ts
  frontend/src/pages/AddChannel/index.tsx
  frontend/src/pages/AddChannel/style.ts
  frontend/src/pages/Bookmark/index.tsx
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/Feed/style.ts
  frontend/src/pages/Home/index.tsx
  frontend/src/pages/Home/style.ts
  frontend/src/pages/Reminder/index.tsx
  frontend/src/pages/SearchResult/index.tsx
  frontend/src/pages/SpecificDateFeed/index.tsx
Labels: 🎁 FE, ⚙️ REFACTOR

#632 hotfix: redirect_uri 수정
  frontend/src/@constants/path.ts
Labels: 🎁 FE, 🚨 HOTFIX

#634 feat: 슬랙 API 호출 예외 메시지 구체화
  backend/src/main/java/com/pickpick/exception/SlackApiCallException.java
  backend/src/main/java/com/pickpick/support/SlackClient.java
Labels: 🎉 BE, ⚙️ REFACTOR

#636 fix: SlackBot은 DB에 저장하지 않도록 수정
  backend/src/main/java/com/pickpick/support/SlackClient.java
Labels: 🎉 BE, 🚨 HOTFIX

#638 fix: 워크스페이스 등록시 oauth.v2.access를 1회만 호출하도록 수정
  backend/src/main/java/com/pickpick/auth/application/AuthService.java
  backend/src/main/java/com/pickpick/auth/application/dto/WorkspaceInfoDto.java
  backend/src/main/java/com/pickpick/support/SlackClient.java
  backend/src/test/java/com/pickpick/support/FakeClient.java
Labels: 🎉 BE, 🚨 HOTFIX

#637 refactor: SlackClient 로직 개선 및 로깅 추가
  backend/src/main/java/com/pickpick/support/SlackClient.java
  backend/src/main/java/com/pickpick/support/SlackFunction.java
  backend/src/test/java/com/pickpick/auth/application/AuthServiceTest.java
  backend/src/test/java/com/pickpick/channel/application/ChannelServiceTest.java
Labels: 🎉 BE, ✨ FEAT

#643 hotfix: 슬랙 로그인 URL 변경
  frontend/src/@constants/path.ts
Labels: 🎁 FE, 🚨 HOTFIX

#644 hotfix: 슬랙 URL scope 제거
  frontend/src/@constants/path.ts
Labels: 🎁 FE, 🚨 HOTFIX

#646 fix: 채널이 삭제되지 않는 현상 개선
  backend/src/main/java/com/pickpick/channel/domain/ChannelSubscriptionRepository.java
  backend/src/main/java/com/pickpick/slackevent/application/channel/ChannelDeletedService.java
  backend/src/test/java/com/pickpick/slackevent/application/channel/ChannelDeletedServiceTest.java
Labels: 🐛 BUG, 🎉 BE

#627 refactor: 워크스페이스 개인화 작업 이후 테스트코드 리팩토링 및 slackClient 모킹 제거
  backend/src/main/java/com/pickpick/auth/application/AuthService.java
  backend/src/main/java/com/pickpick/channel/application/ChannelService.java
  backend/src/main/java/com/pickpick/channel/domain/Channel.java
  backend/src/main/java/com/pickpick/member/domain/Member.java
  backend/src/main/java/com/pickpick/member/domain/MemberRepository.java
  backend/src/main/java/com/pickpick/message/application/ReminderSender.java
  backend/src/main/java/com/pickpick/support/ExternalClient.java
  backend/src/main/java/com/pickpick/support/SlackClient.java
  backend/src/test/java/com/pickpick/acceptance/AcceptanceTestBase.java
  backend/src/test/java/com/pickpick/acceptance/auth/AuthAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/channel/ChannelAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/channel/ChannelSubscriptionAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/BookmarkAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/MessageAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/ChannelEventAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/MemberEventAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/MessageEventAcceptanceTest.java
  backend/src/test/java/com/pickpick/auth/application/AuthServiceTest.java
  backend/src/test/java/com/pickpick/channel/application/ChannelServiceTest.java
  backend/src/test/java/com/pickpick/channel/application/ChannelSubscriptionServiceTest.java
  backend/src/test/java/com/pickpick/channel/domain/ChannelSubscriptionTest.java
  backend/src/test/java/com/pickpick/fixture/ChannelFixture.java
  backend/src/test/java/com/pickpick/fixture/MemberFixture.java
  backend/src/test/java/com/pickpick/fixture/MessageFixture.java
  backend/src/test/java/com/pickpick/fixture/ParticipationFixture.java
  backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
  backend/src/test/java/com/pickpick/message/application/MessageServiceTest.java
  backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/channel/ChannelDeletedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageChangedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageCreatedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageDeletedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageFileShareServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastServiceTest.java
  backend/src/test/java/com/pickpick/support/FakeClient.java
  backend/src/test/java/com/pickpick/support/TestConfig.java
Labels: 🎉 BE, ⚙️ REFACTOR, 💯 TEST

#641 feat: 메시지 text 내부에서 멘션된 slackId를 닉네임으로 대치
  backend/src/main/java/com/pickpick/member/domain/MemberRepository.java
  backend/src/main/java/com/pickpick/message/application/BookmarkService.java
  backend/src/main/java/com/pickpick/message/application/MessageService.java
  backend/src/main/java/com/pickpick/message/application/ReminderService.java
  backend/src/main/java/com/pickpick/message/support/SlackIdExtractor.java
  backend/src/main/java/com/pickpick/message/ui/dto/BookmarkResponse.java
  backend/src/main/java/com/pickpick/message/ui/dto/MessageResponse.java
  backend/src/main/java/com/pickpick/message/ui/dto/ReminderResponse.java
  backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
  backend/src/test/java/com/pickpick/message/application/MessageServiceTest.java
  backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java
  backend/src/test/java/com/pickpick/message/support/SlackIdExtractorTest.java
Labels: 🎉 BE, ✨ FEAT

#642 feat: 이미 존재하는 워크스페이스 등록시 400 Custom Exception 발생하도록 추가
  backend/src/main/java/com/pickpick/auth/application/AuthService.java
  backend/src/main/java/com/pickpick/exception/workspace/WorkspaceDuplicateException.java
  backend/src/main/java/com/pickpick/workspace/domain/WorkspaceRepository.java
  backend/src/test/java/com/pickpick/acceptance/auth/AuthAcceptanceTest.java
  backend/src/test/java/com/pickpick/auth/application/AuthServiceTest.java
Labels: 🎉 BE, ✨ FEAT

#649 refactor: 리마인더 로직 개선
  backend/src/main/java/com/pickpick/message/application/ReminderSender.java
  backend/src/main/java/com/pickpick/message/domain/ReminderRepository.java
  backend/src/test/java/com/pickpick/message/application/ReminderSenderTest.java
Labels: 🎉 BE, 🛠 FIX

#652 refactor: 웹 접근성 반영 2차
  frontend/src/@utils/date.ts
  frontend/src/api/auth.ts
  frontend/src/components/@layouts/Navigation/index.tsx
  frontend/src/components/AddReminder/DateTimePicker/DatePicker/index.tsx
  frontend/src/components/AddReminder/DateTimePicker/DateTimePickerOptions/index.tsx
  frontend/src/components/AddReminder/DateTimePicker/DateTimePickerToggle/index.tsx
  frontend/src/components/AddReminder/DateTimePicker/DateTimePickerToggle/style.ts
  frontend/src/components/AddReminder/DateTimePicker/TimePicker/index.tsx
  frontend/src/components/AddReminder/index.tsx
  frontend/src/components/AddReminder/style.ts
  frontend/src/components/Calendar/index.tsx
  frontend/src/components/ChannelsDrawer/index.tsx
  frontend/src/components/ChannelsDrawer/style.ts
  frontend/src/components/MessageCard/MessageIconButtons/BookmarkButton/index.tsx
  frontend/src/components/MessageCard/MessageIconButtons/ReminderButton/index.tsx
  frontend/src/components/SearchForm/SearchOptions/index.tsx
  frontend/src/components/ThemeToggler/index.tsx
  frontend/src/hooks/@query/useMutateReminder.ts
  frontend/src/hooks/@shared/useFocus.ts
  frontend/src/hooks/useAuthentication.ts
  frontend/src/hooks/useModeTheme.ts
  frontend/src/pages/Bookmark/index.tsx
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/Reminder/index.tsx
  frontend/src/pages/SearchResult/index.tsx
  frontend/src/pages/SpecificDateFeed/index.tsx
Labels: 🎁 FE, ⚙️ REFACTOR

#651 feat: 멘션에 @ 기호 추가
  backend/src/main/java/com/pickpick/message/application/BookmarkService.java
  backend/src/main/java/com/pickpick/message/application/MessageService.java
  backend/src/main/java/com/pickpick/message/application/ReminderService.java
  backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
  backend/src/test/java/com/pickpick/message/application/MessageServiceTest.java
  backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java
Labels: 🎉 BE, ✨ FEAT

#653 hotfix: 중복된 워크스페이스 에러 메시지 추가
  frontend/src/@constants/api.ts
  frontend/src/@constants/message.ts
Labels: 🎁 FE, 🚨 HOTFIX

#654 docs: 리드미 기술스택 추가 및 스토리북 주소 변경
  README.md
Labels: 🌈 ALL, 📝 DOCS

#655 hotfix: tabindex 및 useFocus 제거
  frontend/src/components/AddReminder/DateTimePicker/DateTimePickerOptions/index.tsx
  frontend/src/components/AddReminder/index.tsx
  frontend/src/components/ChannelsDrawer/index.tsx
  frontend/src/components/DateDropdown/DateDropdownMenu/index.tsx
  frontend/src/components/DateDropdown/DateDropdownOption/index.tsx
  frontend/src/components/DateDropdown/index.tsx
  frontend/src/components/MessageCard/MessageIconButtons/BookmarkButton/index.tsx
  frontend/src/components/MessageCard/MessageIconButtons/ReminderButton/index.tsx
  frontend/src/components/MessageCard/index.tsx
  frontend/src/components/SearchForm/SearchOptions/index.tsx
  frontend/src/pages/Bookmark/index.tsx
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/Reminder/index.tsx
  frontend/src/pages/SearchResult/index.tsx
  frontend/src/pages/SpecificDateFeed/index.tsx
Labels: 🎁 FE, 🚨 HOTFIX

#657 hotfix: autofocus 제거
  frontend/src/components/Calendar/index.tsx
  frontend/src/components/ChannelsDrawer/index.tsx
Labels: 🎁 FE, 🚨 HOTFIX

#658 refactor: 스토리북 추가 리팩터링
  frontend/.storybook/preview.js
  frontend/src/components/AddReminder/index.stories.js
  frontend/src/components/MessageCard/index.stories.js
  frontend/src/components/SearchForm/index.stories.js
  frontend/src/components/Snackbar/index.stories.js
  frontend/src/mocks/data/messages.ts
  frontend/src/mocks/data/reminders.ts
  frontend/src/mocks/handlers/bookmarks.ts
  frontend/src/mocks/handlers/channels.ts
Labels: 🎁 FE, ⚙️ REFACTOR

#659 docs: 스토리북 주소 수정
  README.md
Labels: 🌈 ALL, 📝 DOCS

#660 refactor: 줍줍 최초 설치 시 로그인 로직 제거
  backend/src/main/java/com/pickpick/auth/application/AuthService.java
  backend/src/main/java/com/pickpick/auth/ui/AuthController.java
  backend/src/test/java/com/pickpick/acceptance/auth/AuthAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/auth/AuthRestHandler.java
  backend/src/test/java/com/pickpick/acceptance/channel/ChannelAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/channel/ChannelSubscriptionAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/BookmarkAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/MessageAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/ChannelEventAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/MemberEventAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/MessageEventAcceptanceTest.java
Labels: 🎉 BE, ⚙️ REFACTOR

#662 hotfix: slack workspace 로직 수정
  frontend/src/pages/RegisterSlackWorkspace/index.tsx
Labels: 🎁 FE, 🚨 HOTFIX

#663 hotfix: workspace 등록 로직 수정
  frontend/src/@constants/message.ts
  frontend/src/hooks/useApiError.ts
  frontend/src/pages/RegisterSlackWorkspace/index.tsx
Labels: 🎁 FE, 🚨 HOTFIX

#668 refactor: 잘못된 파일명 수정 , 불필요한 import 문 제거 ,사용하지 않은 패키지 제거
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/AddReminder/DateTimePicker/DatePicker/index.stories.js
  frontend/src/components/AddReminder/index.tsx
  frontend/src/mocks/data/testResponseData.ts
  frontend/src/pages/Feed/index.tsx
Labels: 🎁 FE, ⚙️ REFACTOR

#671 hotfix: 슬랙 권한 문제 해결
  backend/src/main/java/com/pickpick/auth/application/AuthService.java
  backend/src/main/java/com/pickpick/auth/application/dto/MemberInfoDto.java
  backend/src/main/java/com/pickpick/support/ExternalClient.java
  backend/src/main/java/com/pickpick/support/SlackClient.java
  backend/src/test/java/com/pickpick/support/FakeClient.java
Labels: 🎉 BE, 🚨 HOTFIX

#682 feat: 검색엔진 최적화를 위한 meta tag 설정
  frontend/public/index.html
Labels: 🎁 FE, ✨ FEAT

#683 refactor: 슬랙 관련 URL을 환경변수로 관리
  frontend/.env.development
  frontend/src/@constants/path.ts
  frontend/webpack.dev.js
  frontend/webpack.prod.js
Labels: 🎁 FE, ⚙️ REFACTOR

#680 refactor: @EnableJpaAuditing 설정 클래스 분리
  backend/src/main/java/com/pickpick/PickpickApplication.java
  backend/src/main/java/com/pickpick/config/JpaAuditingConfig.java
  backend/src/test/java/com/pickpick/support/DocsControllerTestBase.java
Labels: 🎉 BE, ⚙️ REFACTOR

#677 feat: 워크스페이스 등록 후 바로 로그인
  backend/src/main/java/com/pickpick/auth/application/AuthService.java
  backend/src/main/java/com/pickpick/auth/application/dto/OAuthAccessInfoDto.java
  backend/src/main/java/com/pickpick/auth/ui/AuthController.java
  backend/src/main/java/com/pickpick/support/ExternalClient.java
  backend/src/main/java/com/pickpick/support/SlackClient.java
  backend/src/main/java/com/pickpick/workspace/application/WorkspaceService.java
  backend/src/main/java/com/pickpick/workspace/ui/WorkspaceController.java
  backend/src/test/java/com/pickpick/acceptance/AcceptanceTestBase.java
  backend/src/test/java/com/pickpick/acceptance/auth/AuthAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/auth/AuthRestHandler.java
  backend/src/test/java/com/pickpick/acceptance/channel/ChannelAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/channel/ChannelSubscriptionAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/BookmarkAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/MessageAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/ChannelEventAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/MemberEventAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/MessageEventAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/workspace/WorkspaceAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/workspace/WorkspaceRestHandler.java
  backend/src/test/java/com/pickpick/auth/application/AuthServiceTest.java
  backend/src/test/java/com/pickpick/support/DocsControllerTestBase.java
  backend/src/test/java/com/pickpick/support/FakeClient.java
  backend/src/test/java/com/pickpick/workspace/application/WorkspaceServiceTest.java
Labels: 🎉 BE, ✨ FEAT

#676 refactor: 슬랙 워크스페이스 등록 플로우 수정
  frontend/src/api/auth.ts
  frontend/src/hooks/@query/useGetRegisterSlackWorkspace.ts
  frontend/src/pages/RegisterSlackWorkspace/index.tsx
Labels: 🎁 FE, ⚙️ REFACTOR

#684 refactor: 랜딩페이지 이용 문구 수정
  frontend/src/pages/Home/index.tsx
  frontend/src/pages/Home/style.ts
Labels: 🎁 FE, ⚙️ REFACTOR

#685 refactor: 스낵바 메시지 어투 수정
  frontend/src/@constants/message.ts
Labels: 🎁 FE, ⚙️ REFACTOR

#686 refactor: Dropdown 컴포넌트에 스크린리더 설명 추가
  frontend/public/mockServiceWorker.js
  frontend/src/components/@shared/Dropdown/index.tsx
  frontend/src/components/DateDropdown/index.tsx
Labels: 🎁 FE, ⚙️ REFACTOR

#678 refactor: 메시지 서비스에서 Querydsl 로직 분리
  backend/src/main/java/com/pickpick/message/application/MessageService.java
  backend/src/main/java/com/pickpick/message/domain/QMessageRepository.java
Labels: 🎉 BE, ⚙️ REFACTOR

#688 v1.2.2 배포
  backend/src/main/java/com/pickpick/PickpickApplication.java
  backend/src/main/java/com/pickpick/auth/application/AuthService.java
  backend/src/main/java/com/pickpick/auth/application/dto/MemberInfoDto.java
  backend/src/main/java/com/pickpick/auth/application/dto/OAuthAccessInfoDto.java
  backend/src/main/java/com/pickpick/auth/ui/AuthController.java
  backend/src/main/java/com/pickpick/config/JpaAuditingConfig.java
  backend/src/main/java/com/pickpick/message/application/MessageService.java
  backend/src/main/java/com/pickpick/message/domain/QMessageRepository.java
  backend/src/main/java/com/pickpick/support/ExternalClient.java
  backend/src/main/java/com/pickpick/support/SlackClient.java
  backend/src/main/java/com/pickpick/workspace/application/WorkspaceService.java
  backend/src/main/java/com/pickpick/workspace/ui/WorkspaceController.java
  backend/src/test/java/com/pickpick/acceptance/AcceptanceTestBase.java
  backend/src/test/java/com/pickpick/acceptance/auth/AuthAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/auth/AuthRestHandler.java
  backend/src/test/java/com/pickpick/acceptance/channel/ChannelAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/channel/ChannelSubscriptionAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/BookmarkAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/MessageAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/ChannelEventAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/MemberEventAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/MessageEventAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/workspace/WorkspaceAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/workspace/WorkspaceRestHandler.java
  backend/src/test/java/com/pickpick/auth/application/AuthServiceTest.java
  backend/src/test/java/com/pickpick/support/DocsControllerTestBase.java
  backend/src/test/java/com/pickpick/support/FakeClient.java
  backend/src/test/java/com/pickpick/workspace/application/WorkspaceServiceTest.java
  frontend/.env.development
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/public/mockServiceWorker.js
  frontend/src/@constants/message.ts
  frontend/src/@constants/path.ts
  frontend/src/api/auth.ts
  frontend/src/components/@shared/Dropdown/index.tsx
  frontend/src/components/AddReminder/DateTimePicker/DatePicker/index.stories.js
  frontend/src/components/AddReminder/index.tsx
  frontend/src/components/DateDropdown/index.tsx
  frontend/src/hooks/@query/useGetRegisterSlackWorkspace.ts
  frontend/src/mocks/data/testResponseData.ts
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/Home/index.tsx
  frontend/src/pages/Home/style.ts
  frontend/src/pages/RegisterSlackWorkspace/index.tsx
  frontend/webpack.dev.js
  frontend/webpack.prod.js
Labels: 🌈 ALL
