Repository woowacourse-teams/2022-pickpick, pull requests merged in 2022-08, with the labels that each got.

#243 fix: Spring Rest Docs 가 배포환경에서도 작동하도록 수정
  backend/build.gradle
  backend/src/docs/asciidoc/index.adoc
Labels: 🎉 BE, 🛠 FIX, 📝 DOCS

#242 test: 프론트엔드 단위 테스트 및 스토리북 빌드/배포 자동화 스크립트 작성
  .github/workflows/frontend-storybook.yml
  .github/workflows/frontend-unit-test.yml
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/__tests__/sample.test.js
  frontend/package-lock.json
  frontend/package.json
Labels: 🎁 FE, 📝 DOCS, 💯 TEST

#246 feat: 달력 컴포넌트 개발
  frontend/src/components/@shared/WrapperButton/index.tsx
  frontend/src/components/@shared/WrapperButton/style.ts
  frontend/src/components/Calendar/index.stories.js
  frontend/src/components/Calendar/index.tsx
  frontend/src/components/Calendar/style.ts
  frontend/src/hooks/useCalendar.ts
Labels: 🎁 FE, ✨ FEAT

#251 feat: Calendar 컴포넌트 적용
  frontend/src/@utils/index.ts
  frontend/src/components/@layouts/Navigation/index.tsx
  frontend/src/components/Calendar/index.tsx
  frontend/src/components/Calendar/style.ts
  frontend/src/components/DropdownMenu/index.tsx
  frontend/src/hooks/usePortal.ts
Labels: 🎁 FE, ✨ FEAT

#252 refactor: MemberInitializer에 빈 주입 및 테스트에서 비활성화
  backend/src/main/java/com/pickpick/config/SlackConfig.java
  backend/src/main/java/com/pickpick/member/application/MemberInitializer.java
  backend/src/main/java/com/pickpick/slackevent/application/message/MessageCreatedService.java
Labels: 🎉 BE, ⚙️ REFACTOR

#249 feat: 북마크 생성 구현
  backend/src/main/java/com/pickpick/message/application/BookmarkService.java
  backend/src/main/java/com/pickpick/message/domain/Bookmark.java
  backend/src/main/java/com/pickpick/message/domain/BookmarkRepository.java
  backend/src/main/java/com/pickpick/message/ui/BookmarkController.java
  backend/src/main/java/com/pickpick/message/ui/dto/BookmarkRequest.java
  backend/src/test/java/com/pickpick/acceptance/AcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/BookmarkAcceptanceTest.java
  backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
  backend/src/test/resources/bookmark.sql
  backend/src/test/resources/truncate.sql
Labels: 🎉 BE, ✨ FEAT

#260 feat: 선택된 채널의 피드만 보여주는 기능
  frontend/src/@constants/index.ts
  frontend/src/@utils/index.ts
  frontend/src/Routes.tsx
  frontend/src/api/messages.ts
  frontend/src/api/utils.ts
  frontend/src/components/Calendar/index.tsx
  frontend/src/components/DateDropdown/index.tsx
  frontend/src/components/DateDropdown/style.ts
  frontend/src/components/Drawer/index.tsx
  frontend/src/components/Drawer/style.ts
  frontend/src/components/Dropdown/index.tsx
  frontend/src/components/Dropdown/style.ts
  frontend/src/components/DropdownMenu/index.tsx
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/SpecificDateFeed/index.tsx
Labels: 🎁 FE, ✨ FEAT

#268 feat: 북마크 API 명세 수정 반영
  frontend/src/api/bookmarks.ts
Labels: 🎁 FE, ✨ FEAT

#257 feat: 북마크 조회 기능 구현
  backend/src/main/java/com/pickpick/exception/BookmarkNotFoundException.java
  backend/src/main/java/com/pickpick/message/application/BookmarkService.java
  backend/src/main/java/com/pickpick/message/domain/BookmarkRepository.java
  backend/src/main/java/com/pickpick/message/ui/BookmarkController.java
  backend/src/main/java/com/pickpick/message/ui/dto/BookmarkResponse.java
  backend/src/main/java/com/pickpick/message/ui/dto/BookmarkResponses.java
  backend/src/test/java/com/pickpick/acceptance/AcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/BookmarkAcceptanceTest.java
  backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
  backend/src/test/resources/bookmark.sql
Labels: 🎉 BE, ✨ FEAT

#262 feat: 인증 인가 및 로그아웃 기능
  frontend/src/@atoms/index.ts
  frontend/src/@constants/index.ts
  frontend/src/@types/shared.ts
  frontend/src/@utils/index.ts
  frontend/src/Routes.tsx
  frontend/src/api/auth.ts
  frontend/src/api/bookmarks.ts
  frontend/src/api/channels.ts
  frontend/src/api/index.ts
  frontend/src/api/messages.ts
  frontend/src/api/utils.ts
  frontend/src/components/@layouts/Header/index.tsx
  frontend/src/components/@layouts/LayoutContainer/index.tsx
  frontend/src/components/@layouts/Navigation/index.tsx
  frontend/src/components/@layouts/Navigation/style.ts
  frontend/src/components/PrivateRouter/index.tsx
  frontend/src/components/PublicRouter/index.tsx
  frontend/src/components/Snackbar/index.tsx
  frontend/src/components/Snackbar/style.ts
  frontend/src/hooks/useAuthentication.ts
  frontend/src/hooks/useSnackbar.ts
  frontend/src/mocks/handlers/auth.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/pages/index.tsx
Labels: 🎁 FE, ✨ FEAT

#272 feat: 저장소의 Jenkinsfile 삭제
  backend/Jenkinsfile
Labels: 🎉 BE, 🏗 INFRA

#274 feat: Jenkinsfile 삭제
  backend/Jenkinsfile
Labels: 🎉 BE, 🏗 INFRA

#271 refactor: usePortal 리팩터링
  frontend/src/components/@layouts/Navigation/index.tsx
  frontend/src/components/DateDropdown/index.tsx
  frontend/src/hooks/useMessageDate.ts
  frontend/src/hooks/useModal.ts
  frontend/src/hooks/usePortal.ts
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/SpecificDateFeed/index.tsx
  frontend/tsconfig.json
Labels: 🎁 FE, ✨ FEAT

#269 feat: 북마크 삭제 기능 구현
  backend/src/main/java/com/pickpick/exception/BookmarkDeleteFailureException.java
  backend/src/main/java/com/pickpick/message/application/BookmarkService.java
  backend/src/main/java/com/pickpick/message/domain/BookmarkRepository.java
  backend/src/main/java/com/pickpick/message/ui/BookmarkController.java
  backend/src/test/java/com/pickpick/acceptance/BookmarkAcceptanceTest.java
  backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
Labels: 🎉 BE, ✨ FEAT

#275 feat: 채널 구독 순서 예외 케이스 처리
  backend/src/main/java/com/pickpick/channel/application/ChannelSubscriptionService.java
  backend/src/main/java/com/pickpick/channel/domain/ChannelSubscription.java
  backend/src/main/java/com/pickpick/exception/SubscriptionNotExistException.java
  backend/src/main/java/com/pickpick/exception/SubscriptionOrderDuplicateException.java
  backend/src/main/java/com/pickpick/exception/SubscriptionOrderMinException.java
  backend/src/test/java/com/pickpick/acceptance/AcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/ChannelSubscriptionAcceptanceTest.java
  backend/src/test/java/com/pickpick/channel/ChannelSubscriptionServiceTest.java
  backend/src/test/java/com/pickpick/channel/domain/ChannelSubscriptionTest.java
Labels: 🎉 BE, ⚙️ REFACTOR

#261 feat: 메시지 조회 API 에 channelId가 전달되지 않을 경우 로직 수정
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/com/pickpick/channel/domain/ChannelSubscriptionRepository.java
  backend/src/main/java/com/pickpick/exception/SubscriptionNotFoundException.java
  backend/src/main/java/com/pickpick/message/application/MessageService.java
  backend/src/main/java/com/pickpick/message/ui/MessageController.java
  backend/src/test/java/com/pickpick/acceptance/AcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/MessageAcceptanceTest.java
  backend/src/test/java/com/pickpick/controller/MessageControllerTest.java
  backend/src/test/java/com/pickpick/message/MessageServiceTest.java
  backend/src/test/resources/message.sql
Labels: 🎉 BE, ✨ FEAT

#277 feat: 메시지 조회 시 needPastMessage 함께 응답하도록 수정
  backend/src/main/java/com/pickpick/message/application/MessageService.java
  backend/src/main/java/com/pickpick/message/ui/dto/MessageResponses.java
  backend/src/test/java/com/pickpick/acceptance/MessageAcceptanceTest.java
  backend/src/test/java/com/pickpick/controller/MessageControllerTest.java
Labels: 🎉 BE, ⚙️ REFACTOR

#281 feat: 슬랙 OAuth 기능 구현
  frontend/src/@constants/index.ts
  frontend/src/Routes.tsx
  frontend/src/api/auth.ts
  frontend/src/components/@layouts/Header/index.tsx
  frontend/src/hooks/useGetSearchParam.ts
  frontend/src/mocks/handlers/auth.ts
  frontend/src/pages/Certification/index.tsx
  frontend/src/pages/index.tsx
Labels: 🎁 FE, ✨ FEAT

#285 hotifx: axios 요청에서 header 누락되는 문제 해결
  frontend/src/api/auth.ts
  frontend/src/api/bookmarks.ts
  frontend/src/api/channels.ts
  frontend/src/api/index.ts
  frontend/src/api/messages.ts
  frontend/src/components/@layouts/Navigation/index.tsx
Labels: 🎁 FE, 🚨 HOTFIX

#286 hotfix: axios 인스턴스 수정하여 요청 headers 필요시 구분
  frontend/src/api/auth.ts
  frontend/src/api/bookmarks.ts
  frontend/src/api/channels.ts
  frontend/src/api/index.ts
  frontend/src/api/messages.ts
Labels: 🎁 FE, 🚨 HOTFIX

#282 refactor: DateDropdown 컴포넌트 리팩터링
  frontend/src/@constants/index.ts
  frontend/src/@utils/index.ts
  frontend/src/components/DateDropdown/index.tsx
  frontend/src/components/DateDropdownMenu/index.stories.js
  frontend/src/components/DateDropdownMenu/index.tsx
  frontend/src/components/DateDropdownMenu/style.ts
  frontend/src/components/DateDropdownOption/index.tsx
  frontend/src/components/DateDropdownToggle/index.stories.js
  frontend/src/components/DateDropdownToggle/index.tsx
  frontend/src/components/DateDropdownToggle/style.ts
  frontend/src/components/DropdownMenu/index.stories.js
  frontend/src/components/DropdownMenu/index.tsx
  frontend/src/components/DropdownToggle/index.stories.js
Labels: 🎁 FE, ⚙️ REFACTOR

#276 feat: 토큰 인증 및 인가 구현
  backend/src/main/java/com/pickpick/auth/support/AuthenticationPrincipal.java
  backend/src/main/java/com/pickpick/auth/support/JwtTokenProvider.java
  backend/src/main/java/com/pickpick/auth/ui/AuthenticationInterceptor.java
  backend/src/main/java/com/pickpick/auth/ui/AuthenticationPrincipalArgumentResolver.java
  backend/src/main/java/com/pickpick/channel/ui/ChannelController.java
  backend/src/main/java/com/pickpick/channel/ui/ChannelSubscriptionController.java
  backend/src/main/java/com/pickpick/config/AuthenticationPrincipalConfig.java
  backend/src/main/java/com/pickpick/exception/InvalidTokenException.java
  backend/src/main/java/com/pickpick/message/ui/BookmarkController.java
  backend/src/main/java/com/pickpick/message/ui/MessageController.java
  backend/src/test/java/com/pickpick/acceptance/AcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/AuthAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/BookmarkAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/ChannelAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/ChannelSubscriptionAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/MessageAcceptanceTest.java
  backend/src/test/java/com/pickpick/auth/support/JwtTokenProviderTest.java
  backend/src/test/java/com/pickpick/controller/ChannelControllerTest.java
  backend/src/test/java/com/pickpick/controller/ChannelSubscriptionControllerTest.java
  backend/src/test/java/com/pickpick/controller/MessageControllerTest.java
Labels: 🎉 BE, ✨ FEAT

#289 feat: 사용자 인증 관련 API 연동 및 실제 토큰 삽입
  frontend/src/@constants/index.ts
  frontend/src/@utils/index.ts
  frontend/src/api/auth.ts
  frontend/src/api/index.ts
  frontend/src/api/utils.ts
  frontend/src/components/PrivateRouter/index.tsx
  frontend/src/components/PublicRouter/index.tsx
  frontend/src/mocks/handlers/auth.ts
Labels: 🎁 FE, ✨ FEAT

#287 feat: 토큰 검증 api 구현
  backend/src/main/java/com/pickpick/auth/application/AuthService.java
  backend/src/main/java/com/pickpick/auth/ui/AuthController.java
  backend/src/main/java/com/pickpick/config/AuthenticationPrincipalConfig.java
  backend/src/test/java/com/pickpick/acceptance/AuthAcceptanceTest.java
  backend/src/test/java/com/pickpick/auth/application/AuthServiceTest.java
Labels: 🎉 BE, ✨ FEAT

#290 hotfix: 슬랙 로그인 후 토큰 쿠키에 저장하는 로직 추가
  frontend/src/@types/shared.ts
  frontend/src/api/auth.ts
  frontend/src/pages/Certification/index.tsx
Labels: 🎁 FE, 🚨 HOTFIX

#293 feat: logback maxHistory 수정. 5 -> 2
  backend/src/main/resources/appenders/async-file-appender-info.xml
Labels: 🎉 BE, ✨ FEAT

#292 test: util 함수 test 코드 작성
  frontend/.babelrc
  frontend/__tests__/sample.test.js
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/@constants/index.ts
  frontend/src/@types/shared.ts
  frontend/src/@utils/index.test.ts
  frontend/src/@utils/index.ts
  frontend/src/mocks/data/testResponseData.ts
  frontend/src/mocks/handlers/bookmarks.ts
Labels: 🎁 FE, 💯 TEST

#295 hotfix: 사용자 인증 api 요청 retry 횟수 수정 및 디폴트 Query param value 수정
  frontend/src/api/bookmarks.ts
  frontend/src/components/PrivateRouter/index.tsx
  frontend/src/components/PublicRouter/index.tsx
Labels: 🎁 FE, 🚨 HOTFIX

#296 hotfix: 슬랙 로그인 후 쿼리 무효화 추가하여 인증 상태 재검증 하도록 수정
  frontend/src/api/auth.ts
  frontend/src/components/PrivateRouter/index.tsx
  frontend/src/components/PublicRouter/index.tsx
  frontend/src/hooks/useAuthentication.ts
  frontend/src/pages/Certification/index.tsx
Labels: 🎁 FE, 🚨 HOTFIX

#298 fix: 파일 메시지 revert (#225)
  backend/src/main/java/com/pickpick/slackevent/application/SlackEvent.java
  backend/src/main/java/com/pickpick/slackevent/application/message/MessageCreatedService.java
  backend/src/main/java/com/pickpick/slackevent/application/message/MessageFileShareService.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageCreatedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageFileShareServiceTest.java
Labels: 🎉 BE, 🛠 FIX

#302 hotfix : 로그인/로그아웃 버그
  frontend/src/Routes.tsx
  frontend/src/api/auth.ts
  frontend/src/api/bookmarks.ts
  frontend/src/api/channels.ts
  frontend/src/api/index.ts
  frontend/src/api/messages.ts
  frontend/src/api/utils.ts
  frontend/src/hooks/useAuthentication.ts
  frontend/src/pages/Home/index.tsx
Labels: 🎁 FE, 🚨 HOTFIX

#303 feat: 로그인 시 최초 로그인 여부 응답
  backend/src/main/java/com/pickpick/auth/application/AuthService.java
  backend/src/main/java/com/pickpick/auth/ui/AuthController.java
  backend/src/main/java/com/pickpick/auth/ui/dto/LoginResponse.java
  backend/src/main/java/com/pickpick/member/domain/Member.java
  backend/src/test/java/com/pickpick/auth/application/AuthServiceTest.java
  backend/src/test/resources/bookmark.sql
  backend/src/test/resources/channel.sql
  backend/src/test/resources/member.sql
  backend/src/test/resources/message.sql
Labels: 🎉 BE, ✨ FEAT

#304 hotfix: 누락된 headers 추가
  frontend/package.json
  frontend/src/api/messages.ts
Labels: 🎁 FE, 🚨 HOTFIX

#306 feat: 최초 사용자 채널 구독 페이지로 이동하도록 구현
  frontend/src/@types/shared.ts
  frontend/src/hooks/useAuthentication.ts
  frontend/src/mocks/handlers/auth.ts
  frontend/src/pages/Certification/index.tsx
Labels: 🎁 FE, ✨ FEAT

#305 feat: 메시지 응답 필드에 isBookmarked 추가
  backend/src/main/java/com/pickpick/message/application/MessageService.java
  backend/src/main/java/com/pickpick/message/domain/BookmarkRepository.java
  backend/src/main/java/com/pickpick/message/ui/dto/MessageResponse.java
  backend/src/test/java/com/pickpick/controller/MessageControllerTest.java
  backend/src/test/resources/message.sql
Labels: 🎉 BE, ✨ FEAT

#308 feat: 메인페이지에서 북마크 추가 기능 구현
  frontend/package.json
  frontend/src/@types/shared.ts
  frontend/src/mocks/data/testResponseData.ts
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/SpecificDateFeed/index.tsx
Labels: 🎁 FE, ✨ FEAT

#310 hotfix: 채널 선택시 리렌더링 되지 않는 문제 해결
  frontend/src/pages/Feed/index.tsx
Labels: 🎁 FE, 🚨 HOTFIX

#311 hotfix: 선택된 채널 다시 선택했을 경우 drawer 닫히지 않는 버그 수정
  frontend/src/components/@layouts/Navigation/index.tsx
  frontend/src/components/Drawer/index.tsx
Labels: 🎁 FE, 🚨 HOTFIX

#312 hotfix: 메인피드에서 날짜 이동 시, channelId 누락되는 문제 해결
  frontend/src/pages/Feed/index.tsx
Labels: 🎁 FE, 🚨 HOTFIX

#315 docs: README 업데이트
  README.md
Labels: 🌈 ALL, 📝 DOCS

#317 hotfix: 누락된 북마크 상태 추가 및 잘못된 query param 수정
  frontend/src/api/messages.ts
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/SpecificDateFeed/index.tsx
Labels: 🎁 FE, 🚨 HOTFIX

#324 fix: 모든 멤버가 본인으로 뜨는 에러 해결
  backend/src/main/java/com/pickpick/message/application/MessageService.java
  backend/src/main/java/com/pickpick/message/ui/dto/MessageResponse.java
Labels: 🎉 BE, 🚨 HOTFIX

#325 fix: Slack Redirect Url 환경변수로 등록
  frontend/.env.development
  frontend/src/components/@layouts/Header/index.tsx
  frontend/src/pages/Home/index.tsx
  frontend/webpack.dev.js
  frontend/webpack.prod.js
Labels: 🎁 FE, 🛠 FIX

#326 hotfix: 북마크 메시지의 유저가 본인으로 보이는 오류 정정
  backend/src/main/java/com/pickpick/message/ui/dto/BookmarkResponse.java
Labels: 🎉 BE, 🚨 HOTFIX

#327 hotfix: 메시지 본문에 작성자 썸네일 주소가 들어가는 오류 수정
  backend/src/main/java/com/pickpick/message/application/MessageService.java
Labels: 🐛 BUG, 🎉 BE, 🚨 HOTFIX

#328 hotfix: 로그아웃 에러 수정
  frontend/src/@utils/index.ts
Labels: 🎁 FE, 🚨 HOTFIX

#329 hotfix: 잘못된 queryParam 수정
  frontend/src/api/messages.ts
Labels: 🎁 FE, 🚨 HOTFIX

#278 refactor: 채널 구독 예외 케이스 리뷰 반영
  backend/src/main/java/com/pickpick/channel/application/ChannelSubscriptionService.java
  backend/src/main/java/com/pickpick/channel/domain/ChannelSubscription.java
  backend/src/main/java/com/pickpick/exception/SubscriptionInvalidOrderException.java
  backend/src/main/java/com/pickpick/exception/SubscriptionNotExistException.java
  backend/src/main/java/com/pickpick/exception/SubscriptionOrderDuplicateException.java
  backend/src/test/java/com/pickpick/channel/domain/ChannelSubscriptionTest.java
Labels: 🎉 BE, 💄 STYLE

#319 feat: local, dev 환경에서만 CORS 허용
  backend/src/main/java/com/pickpick/config/CorsConfig.java
Labels: 🎉 BE, ✨ FEAT

#297 refactor: 피드백 반영
  backend/src/main/java/com/pickpick/message/application/MessageService.java
Labels: 🎉 BE, ⚙️ REFACTOR

#321 feat: Slack 관련 프로퍼티 객체로 관리하도록 적용
  backend/build.gradle
  backend/src/main/java/com/pickpick/PickpickApplication.java
  backend/src/main/java/com/pickpick/auth/application/AuthService.java
  backend/src/main/java/com/pickpick/config/SlackConfig.java
  backend/src/main/java/com/pickpick/config/SlackProperties.java
Labels: 🎉 BE, ⚙️ REFACTOR

#355 refactor: 북마크 조회, 삭제 api 변경
  backend/src/main/java/com/pickpick/message/application/BookmarkService.java
  backend/src/main/java/com/pickpick/message/domain/BookmarkRepository.java
  backend/src/main/java/com/pickpick/message/ui/BookmarkController.java
  backend/src/main/java/com/pickpick/message/ui/dto/BookmarkResponse.java
  backend/src/test/java/com/pickpick/acceptance/message/BookmarkAcceptanceTest.java
  backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
Labels: 🎉 BE, ✨ FEAT

#356 feat: 북마크 컨트롤러 테스트 및 RESTdocs 추가
  backend/src/docs/asciidoc/index.adoc
  backend/src/test/java/com/pickpick/message/ui/BookmarkControllerTest.java
Labels: 🎉 BE, ✨ FEAT

#361 feat: 프로필 이미지가 없을 경우 대체 이미지 적용
  frontend/public/assets/images/DefaultProfileImage.png
  frontend/src/components/MessageCard/index.tsx
  frontend/src/components/ProfileImage/index.tsx
Labels: 🎁 FE, ✨ FEAT

#360 fix: 변경된 북마크 API 반영
  frontend/src/api/bookmarks.ts
Labels: 🎁 FE, 🛠 FIX

#357 feat: 데이터 없다는 것을 전달할 수 있는 컴포넌트 개발
  frontend/src/components/EmptyStatus/index.stories.js
  frontend/src/components/EmptyStatus/index.tsx
  frontend/src/hooks/usePushPreviousPage.ts
  frontend/src/pages/Bookmark/index.tsx
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/SpecificDateFeed/index.tsx
Labels: 🎁 FE, ✨ FEAT

#339 fix: isFirstLogin이 항상 true로 반환되던 오류 수정
  backend/src/main/java/com/pickpick/auth/application/AuthService.java
  backend/src/main/java/com/pickpick/auth/ui/AuthController.java
  backend/src/test/java/com/pickpick/auth/application/AuthServiceTest.java
Labels: 🐛 BUG, 🎉 BE

#358 feat: TEAM_JOIN 이벤트 구현
  backend/src/main/java/com/pickpick/slackevent/application/SlackEvent.java
  backend/src/main/java/com/pickpick/slackevent/application/member/MemberJoinService.java
  backend/src/main/java/com/pickpick/slackevent/application/member/dto/MemberJoinDto.java
  backend/src/test/java/com/pickpick/acceptance/member/MemberAcceptanceTest.java
  backend/src/test/java/com/pickpick/slackevent/SlackEventTest.java
  backend/src/test/java/com/pickpick/slackevent/application/member/MemberJoinServiceTest.java
Labels: 🎉 BE, ✨ FEAT

#368 feat: 검색 필터 UI 구현
  frontend/src/@types/shared.ts
  frontend/src/components/@shared/Button/index.tsx
  frontend/src/components/@shared/Button/style.ts
  frontend/src/components/SearchInput/index.tsx
  frontend/src/components/SearchInput/style.ts
  frontend/src/components/SearchOptions/index.tsx
  frontend/src/components/SearchOptions/style.ts
  frontend/src/hooks/useChannelIds.ts
  frontend/src/pages/Bookmark/index.tsx
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/SpecificDateFeed/index.tsx
Labels: 🎁 FE, ✨ FEAT

#367 feat: 예외 클래스별 클라이언트 메시지 및 해당 메시지 조회 메서드 추가
  backend/src/main/java/com/pickpick/exception/BadRequestException.java
  backend/src/main/java/com/pickpick/exception/NotFoundException.java
  backend/src/main/java/com/pickpick/exception/channel/ChannelInvalidNameException.java
  backend/src/main/java/com/pickpick/exception/channel/ChannelNotFoundException.java
  backend/src/main/java/com/pickpick/exception/channel/SubscriptionDuplicateException.java
  backend/src/main/java/com/pickpick/exception/channel/SubscriptionInvalidOrderException.java
  backend/src/main/java/com/pickpick/exception/channel/SubscriptionNotExistException.java
  backend/src/main/java/com/pickpick/exception/channel/SubscriptionNotFoundException.java
  backend/src/main/java/com/pickpick/exception/channel/SubscriptionOrderDuplicateException.java
  backend/src/main/java/com/pickpick/exception/member/MemberInvalidThumbnailUrlException.java
  backend/src/main/java/com/pickpick/exception/member/MemberInvalidUsernameException.java
  backend/src/main/java/com/pickpick/exception/member/MemberNotFoundException.java
  backend/src/main/java/com/pickpick/exception/message/BookmarkDeleteFailureException.java
  backend/src/main/java/com/pickpick/exception/message/BookmarkNotFoundException.java
  backend/src/main/java/com/pickpick/exception/message/MessageNotFoundException.java
  backend/src/main/java/com/pickpick/exception/slackevent/SlackEventNotFoundException.java
  backend/src/main/java/com/pickpick/exception/slackevent/SlackEventServiceNotFoundException.java
Labels: 🎉 BE, ⚙️ REFACTOR

#371 feat: 검색 기능 API 연동 및 SearchResult Page 개발
  frontend/src/@constants/index.ts
  frontend/src/@utils/index.ts
  frontend/src/Routes.tsx
  frontend/src/api/messages.ts
  frontend/src/components/Drawer/style.ts
  frontend/src/components/SearchForm/index.tsx
  frontend/src/components/SearchForm/style.ts
  frontend/src/components/SearchInput/index.tsx
  frontend/src/components/SearchInput/style.ts
  frontend/src/components/SearchOptions/index.tsx
  frontend/src/hooks/useModal.ts
  frontend/src/hooks/useSearchKeywordForm.ts
  frontend/src/hooks/useSelectChannels.ts
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/SearchResult/index.tsx
  frontend/src/pages/SpecificDateFeed/index.tsx
Labels: 🎁 FE, ✨ FEAT

#372 refactor: API 에러 처리 리팩터링
  frontend/src/@constants/index.ts
  frontend/src/@types/shared.ts
  frontend/src/App.tsx
  frontend/src/components/PrivateRouter/index.tsx
  frontend/src/components/PublicRouter/index.tsx
  frontend/src/hooks/useApiError.ts
  frontend/src/index.tsx
  frontend/src/pages/Bookmark/index.tsx
  frontend/src/pages/Certification/index.tsx
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/SpecificDateFeed/index.tsx
  frontend/src/queryClient.ts
Labels: 🎁 FE, ⚙️ REFACTOR

#370 feat: 만료된 토큰 예외 처리 클래스 분리
  backend/src/main/java/com/pickpick/auth/support/JwtTokenProvider.java
  backend/src/main/java/com/pickpick/exception/auth/ExpiredTokenException.java
  backend/src/main/java/com/pickpick/exception/auth/InvalidTokenException.java
  backend/src/test/java/com/pickpick/auth/application/AuthServiceTest.java
  backend/src/test/java/com/pickpick/auth/support/JwtTokenProviderTest.java
Labels: 🎉 BE, ⚙️ REFACTOR

#376 refactor: Dropdown 공용 컴포넌트 작성 및 리팩터링
  frontend/src/components/@layouts/Navigation/style.ts
  frontend/src/components/@shared/Dimmer/style.ts
  frontend/src/components/DateDropdown/index.tsx
  frontend/src/components/Drawer/style.ts
  frontend/src/components/Dropdown/index.tsx
  frontend/src/components/SearchForm/index.tsx
  frontend/src/components/SearchForm/style.ts
  frontend/src/components/SearchOptions/style.ts
  frontend/src/hooks/useDropdown.ts
  frontend/src/pages/Feed/style.ts
Labels: 🎁 FE, ⚙️ REFACTOR

#378 feat: react-query-devtools 설정
  frontend/src/App.tsx
Labels: 🎁 FE, ✨ FEAT

#366 feat: 메시지 리마인더 조회 api 구현
  backend/build.gradle
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/com/pickpick/exception/message/ReminderNotFoundException.java
  backend/src/main/java/com/pickpick/message/application/BookmarkService.java
  backend/src/main/java/com/pickpick/message/application/ReminderService.java
  backend/src/main/java/com/pickpick/message/domain/Reminder.java
  backend/src/main/java/com/pickpick/message/domain/ReminderRepository.java
  backend/src/main/java/com/pickpick/message/ui/ReminderController.java
  backend/src/main/java/com/pickpick/message/ui/dto/ReminderResponse.java
  backend/src/main/java/com/pickpick/message/ui/dto/ReminderResponses.java
  backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java
  backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java
  backend/src/test/java/com/pickpick/message/ui/ReminderControllerTest.java
  backend/src/test/resources/reminder.sql
  backend/src/test/resources/truncate.sql
Labels: 🎉 BE, ✨ FEAT

#385 fix: z-index 수정 및 검색 채널 선택 옵션 버그 수정
  frontend/src/components/@layouts/Navigation/style.ts
  frontend/src/components/Calendar/style.ts
  frontend/src/components/DateDropdownMenu/style.ts
  frontend/src/hooks/useSelectChannels.ts
  frontend/src/pages/Certification/index.tsx
Labels: 🎁 FE, 🛠 FIX

#384 feat: 메시지 리마인더 삭제 API 구현
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/com/pickpick/exception/message/ReminderDeleteFailureException.java
  backend/src/main/java/com/pickpick/message/application/ReminderService.java
  backend/src/main/java/com/pickpick/message/domain/Reminder.java
  backend/src/main/java/com/pickpick/message/domain/ReminderRepository.java
  backend/src/main/java/com/pickpick/message/ui/ReminderController.java
  backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java
  backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java
  backend/src/test/java/com/pickpick/message/ui/ReminderControllerTest.java
Labels: 🎉 BE, ✨ FEAT

#379 refactor: 메세지 조회 시 북마크 join으로 함께 조회
  backend/src/main/java/com/pickpick/message/application/MessageService.java
  backend/src/main/java/com/pickpick/message/ui/dto/MessageResponse.java
Labels: 🎉 BE, ⚙️ REFACTOR

#390 feat: 메시지 리마인더 등록 및 수정 API 구현
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/com/pickpick/exception/message/ReminderUpdateFailureException.java
  backend/src/main/java/com/pickpick/message/application/ReminderService.java
  backend/src/main/java/com/pickpick/message/domain/Reminder.java
  backend/src/main/java/com/pickpick/message/domain/ReminderRepository.java
  backend/src/main/java/com/pickpick/message/ui/ReminderController.java
  backend/src/main/java/com/pickpick/message/ui/dto/ReminderRequest.java
  backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java
  backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java
  backend/src/test/java/com/pickpick/message/ui/ReminderControllerTest.java
Labels: 🎉 BE, ✨ FEAT

#395 feat: 리마인드 메시지 전송 기능 구현
  backend/src/main/java/com/pickpick/PickpickApplication.java
  backend/src/main/java/com/pickpick/auth/application/AuthService.java
  backend/src/main/java/com/pickpick/exception/SlackApiCallException.java
  backend/src/main/java/com/pickpick/exception/SlackClientException.java
  backend/src/main/java/com/pickpick/exception/message/SlackSendMessageFailureException.java
  backend/src/main/java/com/pickpick/message/application/ReminderSender.java
  backend/src/main/java/com/pickpick/message/domain/ReminderRepository.java
  backend/src/main/java/com/pickpick/slackevent/application/message/MessageCreatedService.java
Labels: 🎉 BE, ✨ FEAT

#400 feat: 프론트엔드 lighthouse-ci 적용
  .github/workflows/frontend-lighthouse-ci.yml
  frontend/lighthouserc.js
Labels: 🎁 FE, 📝 DOCS, ⭐️ REQUIRED

#401 feat: 메시지 댓글 이벤트 전달 시 저장 제외
  backend/src/main/java/com/pickpick/slackevent/application/message/MessageCreatedService.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageCreatedServiceTest.java
Labels: 🎉 BE, ✨ FEAT

#398 refactor: LocalDateTime.now()에서 Clock을 파라미터로 받도록 수정
  backend/src/main/java/com/pickpick/config/TimeConfig.java
  backend/src/main/java/com/pickpick/message/application/ReminderService.java
  backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java
  backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java
  backend/src/test/java/com/pickpick/message/ui/ReminderControllerTest.java
Labels: 🎉 BE, ⚙️ REFACTOR

#404 refactor: getMessages API 요청시 query params 리팩터링
  frontend/src/api/messages.ts
Labels: 🎁 FE, ⚙️ REFACTOR

#406 refactor: Channel, Member 도메인 하위 레포지토리 save() 반환형 수정
  backend/src/main/java/com/pickpick/channel/domain/ChannelRepository.java
  backend/src/main/java/com/pickpick/channel/domain/ChannelSubscriptionRepository.java
  backend/src/main/java/com/pickpick/member/domain/MemberRepository.java
  backend/src/main/java/com/pickpick/slackevent/application/message/MessageCreatedService.java
  backend/src/test/java/com/pickpick/auth/application/AuthServiceTest.java
  backend/src/test/java/com/pickpick/channel/application/ChannelSubscriptionServiceTest.java
  backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
  backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/channel/ChannelRenameServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/member/MemberChangedServiceTest.java
Labels: 🎉 BE, ⚙️ REFACTOR

#407 feat: 메시지 조회 시 isSetReminded 필드 추가
  backend/src/main/java/com/pickpick/message/application/MessageService.java
  backend/src/main/java/com/pickpick/message/ui/dto/MessageResponse.java
  backend/src/test/java/com/pickpick/acceptance/channel/ChannelSubscriptionAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/MessageAcceptanceTest.java
  backend/src/test/java/com/pickpick/message/application/MessageServiceTest.java
  backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java
  backend/src/test/java/com/pickpick/message/ui/MessageControllerTest.java
  backend/src/test/resources/message.sql
Labels: 🎉 BE, ✨ FEAT

#409 feat: 리마인더 요청 모달창 UI 구현
  frontend/public/assets/icons/Calendar.svg
  frontend/src/@utils/index.test.ts
  frontend/src/@utils/index.ts
  frontend/src/components/DateTimePickerOptions/index.tsx
  frontend/src/components/DateTimePickerOptions/style.ts
  frontend/src/components/DateTimePickerToggle/index.tsx
  frontend/src/components/DateTimePickerToggle/style.ts
  frontend/src/components/ReminderModal/index.tsx
  frontend/src/components/ReminderModal/style.ts
  frontend/src/hooks/useSetReminder.ts
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/SearchResult/index.tsx
  frontend/src/pages/SpecificDateFeed/index.tsx
Labels: 🎁 FE, ✨ FEAT

#416 hotfix: MessageCard component Props 설정
  frontend/src/components/MessageCard/index.tsx
Labels: 🎁 FE, 🚨 HOTFIX

#411 feat: 다크모드 구현
  frontend/public/assets/icons/MoonIcon.svg
  frontend/public/assets/icons/SunIcon.svg
  frontend/src/@styles/colors.ts
  frontend/src/@styles/theme.ts
  frontend/src/App.tsx
  frontend/src/components/@layouts/Navigation/index.tsx
  frontend/src/components/Drawer/index.tsx
  frontend/src/components/SearchInput/style.ts
  frontend/src/components/ThemeToggler/index.stories.js
  frontend/src/components/ThemeToggler/index.tsx
  frontend/src/components/ThemeToggler/style.ts
  frontend/src/hooks/useModeTheme.ts
  frontend/src/hooks/useWebStorage.ts
  frontend/src/index.tsx
  frontend/src/mocks/index.ts
Labels: 🎁 FE, ✨ FEAT

#419 fix: 로그인 되지 않은 사용자에게 랜딩페이지에서 에러메시지를 띄우는 버그
  frontend/src/components/PublicRouter/index.tsx
  frontend/src/hooks/useModeTheme.ts
Labels: 🎁 FE, 🛠 FIX

#420 fix: 다크모드/라이트모드 토글러 버튼 UI 및 위치 수정
  frontend/.storybook/preview.js
  frontend/public/assets/icons/MoonIcon.svg
  frontend/public/assets/icons/SunIcon.svg
  frontend/src/@atoms/index.ts
  frontend/src/@constants/index.ts
  frontend/src/@types/shared.ts
  frontend/src/App.tsx
  frontend/src/components/Drawer/index.tsx
  frontend/src/components/Drawer/style.ts
  frontend/src/components/ThemeToggler/index.tsx
  frontend/src/components/ThemeToggler/style.ts
  frontend/src/hooks/useModeTheme.ts
Labels: 🎁 FE, 🛠 FIX

#414 feat: message 도메인 하위 repository에서 save시 해당 도메인 반환하도록 변경
  backend/src/main/java/com/pickpick/message/domain/BookmarkRepository.java
  backend/src/main/java/com/pickpick/message/domain/MessageRepository.java
  backend/src/main/java/com/pickpick/message/domain/ReminderRepository.java
  backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
  backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java
Labels: 🎉 BE, ⚙️ REFACTOR

#413 fix: 메시지 조회 시 해당 회원의 북마크일 경우만 isBookmarked: true 반환
  backend/src/main/java/com/pickpick/message/application/MessageService.java
Labels: 🐛 BUG, 🎉 BE

#432 fix: 리마인더 조회 시 메시지 작성자의 정보 전달
  backend/src/main/java/com/pickpick/message/application/ReminderService.java
  backend/src/main/java/com/pickpick/message/ui/dto/ReminderResponse.java
Labels: 🐛 BUG, 🎉 BE

#436 fix: 리마인더 삭제 api 명세가 북마크 삭제 api 명세로 보였던 에러 수정
  backend/src/docs/asciidoc/index.adoc
Labels: 🎉 BE, 📝 DOCS

#427 feat: file_share 이벤트를 저장하는 기능 구현
  backend/src/main/java/com/pickpick/slackevent/application/SlackEvent.java
  backend/src/main/java/com/pickpick/slackevent/application/message/MessageFileShareService.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/MessageEventAcceptanceTest.java
  backend/src/test/java/com/pickpick/slackevent/SlackEventTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageFileShareServiceTest.java
Labels: 🎉 BE, ✨ FEAT

#435 test: 리마인더 단건 조회 관련 service 및 acceptance test 추가
  backend/src/docs/asciidoc/index.adoc
  backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java
  backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java
  backend/src/test/java/com/pickpick/message/ui/ReminderControllerTest.java
Labels: 🎉 BE, 💯 TEST

#440 feat: 메시지 조회 시 remindDate 필드 추가
  backend/src/main/java/com/pickpick/message/application/MessageService.java
  backend/src/main/java/com/pickpick/message/ui/dto/MessageResponse.java
  backend/src/test/java/com/pickpick/acceptance/message/MessageAcceptanceTest.java
  backend/src/test/java/com/pickpick/message/application/MessageServiceTest.java
  backend/src/test/java/com/pickpick/message/ui/MessageControllerTest.java
Labels: 🎉 BE, ✨ FEAT

#423 feat: Reminder와 Bookmark 조회 시 count 추가
  backend/src/main/java/com/pickpick/message/application/BookmarkService.java
  backend/src/main/java/com/pickpick/message/application/ReminderService.java
  backend/src/main/java/com/pickpick/message/ui/BookmarkController.java
  backend/src/main/java/com/pickpick/message/ui/ReminderController.java
  backend/src/main/java/com/pickpick/message/ui/dto/BookmarkFindRequest.java
  backend/src/main/java/com/pickpick/message/ui/dto/ReminderFindRequest.java
  backend/src/main/java/com/pickpick/message/ui/dto/ReminderSaveRequest.java
  backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java
  backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
  backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java
  backend/src/test/java/com/pickpick/message/ui/ReminderControllerTest.java
Labels: 🎉 BE, ✨ FEAT

#439 feat: 리마인더 요청 API 연결
  frontend/src/@constants/index.ts
  frontend/src/@styles/theme.ts
  frontend/src/@types/shared.ts
  frontend/src/@utils/index.test.ts
  frontend/src/@utils/index.ts
  frontend/src/Routes.tsx
  frontend/src/api/reminders.ts
  frontend/src/api/utils.ts
  frontend/src/components/@layouts/Navigation/index.tsx
  frontend/src/components/DateTimePickerOptions/index.tsx
  frontend/src/components/MessageCard/index.tsx
  frontend/src/components/MessageCard/style.ts
  frontend/src/components/MessageIconButtons/BookmarkButton/index.tsx
  frontend/src/components/MessageIconButtons/ReminderButton/index.tsx
  frontend/src/components/MessageIconButtons/style.ts
  frontend/src/components/ReminderModal/index.tsx
  frontend/src/components/ReminderModal/style.ts
  frontend/src/hooks/useInput.ts
  frontend/src/hooks/useMutateReminder.ts
  frontend/src/hooks/useSetReminder.ts
  frontend/src/hooks/useSetTargetMessage.ts
  frontend/src/mocks/data/testResponseData.ts
  frontend/src/pages/Alarm/index.tsx
  frontend/src/pages/Bookmark/index.tsx
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/Reminder/index.tsx
  frontend/src/pages/SearchResult/index.tsx
  frontend/src/pages/SpecificDateFeed/index.tsx
  frontend/src/pages/index.tsx
Labels: 🎁 FE, ✨ FEAT

#433 feat: favicon 추가 및 오픈그래프 메타태그 추가
  frontend/public/assets/images/favicon.ico
  frontend/public/assets/images/pickpick.png
  frontend/public/index.html
Labels: 🎁 FE, ✨ FEAT

#442 chore: Jacoco, SonarQube 연동
  .github/workflows/backend-sonarqube.yml
  backend/build.gradle
Labels: 🎉 BE, 🏗 INFRA, ⭐️ REQUIRED

#424 feat: thread_broadcast 이벤트에 대한 기능 추가
  backend/src/main/java/com/pickpick/slackevent/application/SlackEvent.java
  backend/src/main/java/com/pickpick/slackevent/application/message/MessageChangedService.java
  backend/src/main/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastService.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/MessageEventAcceptanceTest.java
  backend/src/test/java/com/pickpick/slackevent/SlackEventTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageChangedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastServiceTest.java
Labels: 🎉 BE, ✨ FEAT

#451 feat: 코드와 메세지를 가진 ErrorResponse 반환
  backend/src/main/java/com/pickpick/config/ControllerAdvice.java
  backend/src/main/java/com/pickpick/config/dto/ErrorResponse.java
  backend/src/main/java/com/pickpick/exception/BadRequestException.java
  backend/src/main/java/com/pickpick/exception/NotFoundException.java
  backend/src/main/java/com/pickpick/exception/auth/InvalidTokenException.java
  backend/src/main/java/com/pickpick/exception/channel/ChannelNotFoundException.java
  backend/src/main/java/com/pickpick/exception/channel/SubscriptionDuplicateException.java
  backend/src/main/java/com/pickpick/exception/channel/SubscriptionInvalidOrderException.java
  backend/src/main/java/com/pickpick/exception/channel/SubscriptionNotExistException.java
  backend/src/main/java/com/pickpick/exception/channel/SubscriptionNotFoundException.java
  backend/src/main/java/com/pickpick/exception/channel/SubscriptionOrderDuplicateException.java
  backend/src/main/java/com/pickpick/exception/member/MemberNotFoundException.java
  backend/src/main/java/com/pickpick/exception/message/BookmarkDeleteFailureException.java
  backend/src/main/java/com/pickpick/exception/message/BookmarkNotFoundException.java
  backend/src/test/java/com/pickpick/acceptance/auth/AuthAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/channel/ChannelSubscriptionAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/BookmarkAcceptanceTest.java
Labels: 🎉 BE, ✨ FEAT

#453 fix: 배포된 페이지에서 favicon 누락 해결
  frontend/public/index.html
  frontend/webpack.common.js
Labels: 🎁 FE, 🛠 FIX

#443 refactor: 검색 결과 페이지 UI 및 관련 로직 리팩터링
  frontend/src/components/@layouts/Navigation/index.tsx
  frontend/src/components/SearchForm/index.tsx
  frontend/src/components/SearchOptions/index.tsx
  frontend/src/hooks/useGetSearchParam.ts
  frontend/src/hooks/useGetSubscribedChannels.ts
  frontend/src/hooks/useSearchKeywordForm.ts
  frontend/src/hooks/useSelectChannels.ts
  frontend/src/hooks/useSubmitSearchForm.ts
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/SearchResult/index.tsx
  frontend/src/pages/SpecificDateFeed/index.tsx
Labels: 🎁 FE, ⚙️ REFACTOR

#458 fix: 검색 채널 옵션 선택 버그 해결
  frontend/src/hooks/useSelectChannels.ts
Labels: 🎁 FE, 🛠 FIX

#459 fix: 서버 에러 대응 방법 수정 및 구독중인 채널 없을 경우 대응
  frontend/src/@types/shared.ts
  frontend/src/App.tsx
  frontend/src/hooks/useApiError.ts
Labels: 🎁 FE, 🛠 FIX

#461 fix: Storybook 빌드 에러 해결
  frontend/.env.development
  frontend/src/components/@shared/IconButton/index.stories.js
  frontend/src/components/MessageIconButtons/BookmarkButton/index.stories.js
  frontend/src/components/MessageIconButtons/ReminderButton/index.stories.js
Labels: 🎁 FE, 💯 TEST, 🚨 HOTFIX

#462 refactor: 사용하지 않는 assets 제거
  frontend/.env.development
  frontend/public/assets/icons/HomeIcon-Fill.svg
  frontend/public/assets/icons/RemoveIcon.svg
  frontend/public/assets/icons/StarIcon-Fill.svg
Labels: 🎁 FE, ⚙️ REFACTOR

#463 refactor: 누락된 타입 보강 및 타입 리팩터링
  frontend/src/@types/shared.ts
  frontend/src/@utils/index.ts
  frontend/src/api/auth.ts
  frontend/src/api/bookmarks.ts
  frontend/src/api/channels.ts
  frontend/src/api/messages.ts
  frontend/src/api/reminders.ts
  frontend/src/components/@layouts/LayoutContainer/index.tsx
  frontend/src/components/@shared/Button/index.tsx
  frontend/src/components/@shared/IconButton/index.tsx
  frontend/src/components/@shared/InfiniteScroll/index.tsx
  frontend/src/components/@shared/Portal/index.tsx
  frontend/src/components/@shared/WrapperButton/index.tsx
  frontend/src/components/@shared/WrapperLink/index.tsx
  frontend/src/components/DateDropdownToggle/index.tsx
  frontend/src/components/DateTimePickerToggle/index.tsx
  frontend/src/components/Dropdown/index.tsx
  frontend/src/components/EmptyStatus/index.tsx
  frontend/src/components/ErrorBoundary/index.tsx
  frontend/src/components/MessagesLoadingStatus/index.tsx
  frontend/src/components/PublicRouter/index.tsx
  frontend/src/components/ReminderModal/index.tsx
  frontend/src/components/SearchForm/index.tsx
  frontend/src/components/SearchInput/index.tsx
  frontend/src/components/SearchOptions/index.tsx
  frontend/src/hooks/useApiError.ts
  frontend/src/hooks/useAuthentication.ts
  frontend/src/hooks/useBookmark.ts
  frontend/src/hooks/useInput.ts
  frontend/src/hooks/useMutateReminder.ts
  frontend/src/hooks/useSetReminder.ts
  frontend/src/hooks/useSetTargetMessage.ts
  frontend/src/hooks/useTopScreenEventHandlers.ts
  frontend/src/mocks/data/testResponseData.ts
  frontend/src/pages/AddChannel/index.tsx
  frontend/src/pages/Bookmark/index.tsx
  frontend/src/pages/Certification/index.tsx
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/Reminder/index.tsx
  frontend/src/pages/SearchResult/index.tsx
  frontend/src/pages/SpecificDateFeed/index.tsx
Labels: 🎁 FE, ⚙️ REFACTOR

#444 feat: DatabaseCleaner 구현
  backend/src/test/java/com/pickpick/acceptance/AcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/auth/AuthAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/channel/ChannelAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/channel/ChannelSubscriptionAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/member/MemberAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/BookmarkAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/MessageAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/MemberEventAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/MessageEventAcceptanceTest.java
  backend/src/test/java/com/pickpick/channel/ui/ChannelControllerTest.java
  backend/src/test/java/com/pickpick/channel/ui/ChannelSubscriptionControllerTest.java
  backend/src/test/java/com/pickpick/config/DatabaseCleaner.java
  backend/src/test/java/com/pickpick/config/RestDocsTestSupport.java
  backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java
  backend/src/test/java/com/pickpick/message/ui/BookmarkControllerTest.java
  backend/src/test/java/com/pickpick/message/ui/MessageControllerTest.java
  backend/src/test/java/com/pickpick/message/ui/ReminderControllerTest.java
Labels: 🎉 BE, 💯 TEST

#457 refactor: 채널 생성 역할을 channelService에게 위임
  backend/src/main/java/com/pickpick/channel/application/ChannelService.java
  backend/src/main/java/com/pickpick/slackevent/application/message/MessageCreatedService.java
  backend/src/main/java/com/pickpick/slackevent/application/message/MessageFileShareService.java
  backend/src/main/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastService.java
  backend/src/test/java/com/pickpick/channel/application/ChannelServiceTest.java
Labels: 🎉 BE, ⚙️ REFACTOR

#468 feat: 예외 메시지에 데이터도 포함되도록 수정
  backend/src/main/java/com/pickpick/auth/support/JwtTokenProvider.java
  backend/src/main/java/com/pickpick/channel/domain/ChannelSubscription.java
  backend/src/main/java/com/pickpick/exception/auth/ExpiredTokenException.java
  backend/src/main/java/com/pickpick/exception/auth/InvalidTokenException.java
  backend/src/main/java/com/pickpick/exception/channel/SubscriptionInvalidOrderException.java
Labels: 🎉 BE, ✨ FEAT

#469 refactor: QA 1차 반영
  frontend/src/components/@layouts/Navigation/index.tsx
  frontend/src/components/SearchOptions/index.tsx
  frontend/src/hooks/useApiError.ts
  frontend/src/hooks/useAuthentication.ts
  frontend/src/hooks/useRecentFeedPath.ts
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/SearchResult/index.tsx
  frontend/src/pages/SpecificDateFeed/index.tsx
Labels: 🎁 FE, ⚙️ REFACTOR

#470 refactor: QA 2차 반영
  frontend/src/components/@layouts/Footer/index.tsx
  frontend/src/components/Dropdown/index.tsx
  frontend/src/components/SearchForm/index.tsx
  frontend/src/components/Snackbar/style.ts
  frontend/src/hooks/useOuterClick.ts
  frontend/src/pages/Bookmark/index.tsx
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/Reminder/index.tsx
  frontend/src/pages/SpecificDateFeed/index.tsx
Labels: 🎁 FE, ⚙️ REFACTOR

#472 refactor: QA 3차 반영
  frontend/public/assets/icons/HomeIcon.svg
  frontend/public/assets/icons/ReminderIcon-Active.svg
  frontend/public/assets/icons/ReminderIcon-Inactive.svg
  frontend/public/assets/icons/StarIcon.svg
  frontend/public/assets/icons/YoutubeIcon.svg
  frontend/src/@styles/colors.ts
  frontend/src/@styles/theme.ts
  frontend/src/components/@layouts/Navigation/index.tsx
  frontend/src/components/Drawer/index.tsx
  frontend/src/components/Drawer/style.ts
  frontend/src/components/MessageIconButtons/BookmarkButton/index.tsx
  frontend/src/components/MessageIconButtons/ReminderButton/index.tsx
  frontend/src/components/ReminderModal/index.tsx
  frontend/src/hooks/useMutateReminder.ts
  frontend/src/hooks/useSetReminder.ts
Labels: 🎁 FE, ⚙️ REFACTOR

#473 fix: BookmarkResponse에서 bookmark id 도 함께 반환받도록 수정
  backend/src/main/java/com/pickpick/message/ui/dto/BookmarkResponse.java
  backend/src/test/java/com/pickpick/message/ui/BookmarkControllerTest.java
Labels: 🎉 BE, 🚨 HOTFIX

#476 refactor: QA 4차 반영
  frontend/public/assets/icons/MoonIcon.svg
  frontend/public/assets/icons/SunIcon.svg
  frontend/src/@types/shared.ts
  frontend/src/@utils/index.ts
  frontend/src/components/Drawer/index.tsx
  frontend/src/components/ThemeToggler/index.tsx
  frontend/src/components/ThemeToggler/style.ts
  frontend/src/hooks/useModeTheme.ts
  frontend/src/mocks/data/testResponseData.ts
  frontend/src/pages/Bookmark/index.tsx
Labels: 🎁 FE, ⚙️ REFACTOR

#477 refactor: QA5차 반영
  frontend/src/@styles/GlobalStyle.ts
  frontend/src/components/@layouts/LayoutContainer/index.tsx
  frontend/src/pages/AddChannel/index.tsx
  frontend/src/pages/AddChannel/style.ts
Labels: 🎁 FE, ⚙️ REFACTOR, 💄 STYLE

#465 fix: thread_broadcast 메시지 수정 시 수정이 반영되지 않는 버그 수정
  backend/src/main/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastService.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastServiceTest.java
Labels: 🎉 BE, 🛠 FIX

#478 fix: 같은 날 리마인더 개수가 count보다 많은 경우에 isLast 에러 수정
  backend/src/main/java/com/pickpick/message/application/ReminderService.java
  backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java
  backend/src/test/resources/reminder.sql
Labels: 🎉 BE, 🚨 HOTFIX
