Repository woowacourse-teams/2022-pickpick, pull requests merged in 2022-11, with the labels that each got.

#692 docs: 리드미 업데이트
  README.md
Labels: 🌈 ALL, 📝 DOCS

#696 refactor: webpack 불필요한 플러그인 제 및 esbuild-loader로 변경
  frontend/package-lock.json
  frontend/package.json
  frontend/webpack.common.js
  frontend/webpack.dev.js
  frontend/webpack.prod.js
Labels: 🎁 FE, ⚙️ REFACTOR

#699 refactor: package.json scripts 변경
  frontend/package.json
Labels: 🎁 FE, ⚙️ REFACTOR

#693 refactor: 메시지 text에서 멘션 아이디를 대체하는 부분 리팩토링
  backend/src/main/java/com/pickpick/channel/application/ChannelService.java
  backend/src/main/java/com/pickpick/exception/utils/ReflectionFailureException.java
  backend/src/main/java/com/pickpick/message/application/BookmarkService.java
  backend/src/main/java/com/pickpick/message/application/MessageService.java
  backend/src/main/java/com/pickpick/message/application/ReminderService.java
  backend/src/main/java/com/pickpick/message/ui/dto/BookmarkResponse.java
  backend/src/main/java/com/pickpick/message/ui/dto/MessageResponse.java
  backend/src/main/java/com/pickpick/message/ui/dto/ReminderResponse.java
  backend/src/main/java/com/pickpick/support/MentionAspect.java
  backend/src/main/java/com/pickpick/support/MentionIdReplaceable.java
  backend/src/main/java/com/pickpick/utils/SlackIdExtractUtils.java
  backend/src/test/java/com/pickpick/message/support/SlackIdExtractUtilsTest.java
Labels: 🎉 BE, ⚙️ REFACTOR

#707 fix: ReminderSender에서 N+1 문제 개선
  backend/src/main/java/com/pickpick/message/application/ReminderSender.java
  backend/src/main/java/com/pickpick/message/domain/ReminderRepository.java
Labels: 🎉 BE, 🛠 FIX

#708 fix: channel subscription에서 발생하는 n+1 쿼리 해결
  backend/src/main/java/com/pickpick/channel/domain/ChannelSubscriptionRepository.java
Labels: 🎉 BE, 🛠 FIX

#709 fix: ReminderRepository 에서 단일 조회 시 발생하는 쿼리 3개 -> 1개 수정
  backend/src/main/java/com/pickpick/message/domain/ReminderRepository.java
Labels: 🎉 BE, 🛠 FIX
