Repository woowacourse-teams/2022-pickpick, pull requests merged in 2022-09, with the labels that each got.

#482 refactor: 리액트 쿼리 로직 커스텀 훅 분리
  frontend/src/@constants/index.ts
  frontend/src/@utils/index.ts
  frontend/src/api/utils.ts
  frontend/src/components/@layouts/Header/index.tsx
  frontend/src/components/@layouts/LayoutContainer/index.tsx
  frontend/src/components/@layouts/Navigation/index.tsx
  frontend/src/components/ReminderModal/index.tsx
  frontend/src/hooks/query/useGetCertification.ts
  frontend/src/hooks/query/useGetChannels.ts
  frontend/src/hooks/query/useGetInfiniteBookmarks.ts
  frontend/src/hooks/query/useGetInfiniteMessages.ts
  frontend/src/hooks/query/useGetInfiniteReminders.ts
  frontend/src/hooks/query/useGetSubscribedChannels.ts
  frontend/src/hooks/query/useMutateBookmark.ts
  frontend/src/hooks/query/useMutateChannels.ts
  frontend/src/hooks/query/useMutateReminder.ts
  frontend/src/hooks/useRecentFeedPath.ts
  frontend/src/hooks/useSelectChannels.ts
  frontend/src/hooks/useSetReminderTargetMessage.ts
  frontend/src/pages/AddChannel/index.tsx
  frontend/src/pages/Bookmark/index.tsx
  frontend/src/pages/Certification/index.tsx
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/Home/index.tsx
  frontend/src/pages/Reminder/index.tsx
  frontend/src/pages/SearchResult/index.tsx
  frontend/src/pages/SpecificDateFeed/index.tsx
Labels: 🎁 FE, ⚙️ REFACTOR

#487 refactor: MemberAcceptanceTest 내 @Disabled된 테스트 삭제
  backend/src/test/java/com/pickpick/acceptance/member/MemberAcceptanceTest.java
Labels: 🎉 BE, ⚙️ REFACTOR

#492 refactor: MemberInitializer 예외를 프로젝트 예외로 변환
  backend/src/main/java/com/pickpick/member/application/MemberInitializer.java
Labels: 🎉 BE, ⚙️ REFACTOR

#421 refactor: 메시지 조회 테스트 리팩토링
  backend/src/test/java/com/pickpick/fixture/MessageFixtures.java
  backend/src/test/java/com/pickpick/fixture/MessageRequestFactory.java
  backend/src/test/java/com/pickpick/message/application/MessageServiceTest.java
Labels: 🎉 BE, ⚙️ REFACTOR

#495 refactor: 채널 목록 조회 API 개선
  backend/src/main/java/com/pickpick/channel/application/ChannelCreateService.java
  backend/src/main/java/com/pickpick/channel/application/ChannelService.java
  backend/src/main/java/com/pickpick/channel/application/ChannelSubscriptionService.java
  backend/src/main/java/com/pickpick/channel/ui/ChannelController.java
  backend/src/main/java/com/pickpick/channel/ui/ChannelSubscriptionController.java
  backend/src/main/java/com/pickpick/channel/ui/dto/ChannelResponse.java
  backend/src/main/java/com/pickpick/slackevent/application/message/MessageCreatedService.java
  backend/src/main/java/com/pickpick/slackevent/application/message/MessageFileShareService.java
  backend/src/main/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastService.java
  backend/src/test/java/com/pickpick/channel/application/ChannelCreateServiceTest.java
  backend/src/test/java/com/pickpick/channel/application/ChannelServiceTest.java
  backend/src/test/java/com/pickpick/channel/application/ChannelSubscriptionServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/channel/ChannelRenameServiceTest.java
Labels: 🎉 BE, ⚙️ REFACTOR

#504 refactor: AuthorizationExtractor를 auth 패키지로 이동
  backend/src/main/java/com/pickpick/auth/support/AuthorizationExtractor.java
  backend/src/main/java/com/pickpick/auth/ui/AuthController.java
  backend/src/main/java/com/pickpick/auth/ui/AuthenticationInterceptor.java
  backend/src/main/java/com/pickpick/auth/ui/AuthenticationPrincipalArgumentResolver.java
Labels: 🎉 BE, ⚙️ REFACTOR

#512 refacotor: 접근제어자 수정
  backend/src/main/java/com/pickpick/slackevent/application/SlackEventServiceFinder.java
Labels: 🎉 BE, ⚙️ REFACTOR

#498 feat: SlackApiCallException 로깅 메시지 추가
  backend/src/main/java/com/pickpick/auth/application/AuthService.java
  backend/src/main/java/com/pickpick/channel/application/ChannelCreateService.java
  backend/src/main/java/com/pickpick/config/ControllerAdvice.java
  backend/src/main/java/com/pickpick/exception/SlackApiCallException.java
  backend/src/main/java/com/pickpick/member/application/MemberInitializer.java
Labels: 🎉 BE, ✨ FEAT

#513 refactor: 메시지/북마크/리마인더 조회 API 스펙 변경
  backend/src/main/java/com/pickpick/message/application/BookmarkService.java
  backend/src/main/java/com/pickpick/message/application/MessageService.java
  backend/src/main/java/com/pickpick/message/application/ReminderService.java
  backend/src/main/java/com/pickpick/message/ui/dto/BookmarkResponses.java
  backend/src/main/java/com/pickpick/message/ui/dto/MessageResponses.java
  backend/src/main/java/com/pickpick/message/ui/dto/ReminderResponses.java
  backend/src/test/java/com/pickpick/acceptance/message/BookmarkAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/MessageAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/message/ReminderAcceptanceTest.java
  backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
  backend/src/test/java/com/pickpick/message/application/MessageServiceTest.java
  backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java
  backend/src/test/java/com/pickpick/message/ui/BookmarkControllerTest.java
  backend/src/test/java/com/pickpick/message/ui/MessageControllerTest.java
  backend/src/test/java/com/pickpick/message/ui/ReminderControllerTest.java
Labels: 🎉 BE, 🌈 ALL, ⚙️ REFACTOR

#515 refactor: 메시지/북마크/리마인더 조회 API 스펙 변경 대응
  frontend/src/@styles/GlobalStyle.ts
  frontend/src/@types/shared.ts
  frontend/src/@utils/index.test.ts
  frontend/src/components/@shared/WrapperButton/index.stories.js
  frontend/src/hooks/query/useGetInfiniteBookmarks.ts
  frontend/src/hooks/query/useGetInfiniteMessages.ts
  frontend/src/hooks/query/useGetInfiniteReminders.ts
Labels: 🎁 FE, ⚙️ REFACTOR

#508 refactor: HashMap 강제 형변환 제거
  backend/src/main/java/com/pickpick/exception/utils/InvalidJsonRequestException.java
  backend/src/main/java/com/pickpick/slackevent/application/SlackEvent.java
  backend/src/main/java/com/pickpick/slackevent/application/SlackEventService.java
  backend/src/main/java/com/pickpick/slackevent/application/channel/ChannelDeletedService.java
  backend/src/main/java/com/pickpick/slackevent/application/channel/ChannelRenameService.java
  backend/src/main/java/com/pickpick/slackevent/application/channel/dto/ChannelDeletedRequest.java
  backend/src/main/java/com/pickpick/slackevent/application/channel/dto/ChannelDto.java
  backend/src/main/java/com/pickpick/slackevent/application/channel/dto/ChannelRenameRequest.java
  backend/src/main/java/com/pickpick/slackevent/application/channel/dto/SlackChannelRenameDto.java
  backend/src/main/java/com/pickpick/slackevent/application/dto/EventDto.java
  backend/src/main/java/com/pickpick/slackevent/application/dto/SlackEventRequest.java
  backend/src/main/java/com/pickpick/slackevent/application/member/MemberChangedService.java
  backend/src/main/java/com/pickpick/slackevent/application/member/MemberJoinService.java
  backend/src/main/java/com/pickpick/slackevent/application/member/dto/MemberEventDto.java
  backend/src/main/java/com/pickpick/slackevent/application/member/dto/MemberJoinDto.java
  backend/src/main/java/com/pickpick/slackevent/application/member/dto/MemberProfileChangedDto.java
  backend/src/main/java/com/pickpick/slackevent/application/member/dto/MemberRequest.java
  backend/src/main/java/com/pickpick/slackevent/application/member/dto/ProfileDto.java
  backend/src/main/java/com/pickpick/slackevent/application/member/dto/UserDto.java
  backend/src/main/java/com/pickpick/slackevent/application/message/MessageChangedService.java
  backend/src/main/java/com/pickpick/slackevent/application/message/MessageCreatedService.java
  backend/src/main/java/com/pickpick/slackevent/application/message/MessageDeletedService.java
  backend/src/main/java/com/pickpick/slackevent/application/message/MessageFileShareService.java
  backend/src/main/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastService.java
  backend/src/main/java/com/pickpick/slackevent/application/message/dto/MessageChangedEventDto.java
  backend/src/main/java/com/pickpick/slackevent/application/message/dto/MessageChangedRequest.java
  backend/src/main/java/com/pickpick/slackevent/application/message/dto/MessageCreatedEventDto.java
  backend/src/main/java/com/pickpick/slackevent/application/message/dto/MessageCreatedRequest.java
  backend/src/main/java/com/pickpick/slackevent/application/message/dto/MessageDeletedEventDto.java
  backend/src/main/java/com/pickpick/slackevent/application/message/dto/MessageDeletedRequest.java
  backend/src/main/java/com/pickpick/slackevent/application/message/dto/MessageDto.java
  backend/src/main/java/com/pickpick/slackevent/application/message/dto/PreviousMessageDto.java
  backend/src/main/java/com/pickpick/slackevent/application/message/dto/SlackMessageDto.java
  backend/src/main/java/com/pickpick/slackevent/ui/SlackEventController.java
  backend/src/main/java/com/pickpick/slackevent/ui/dto/ChallengeRequest.java
  backend/src/main/java/com/pickpick/utils/JsonUtils.java
  backend/src/test/java/com/pickpick/acceptance/member/MemberAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/slackevent/MemberEventAcceptanceTest.java
  backend/src/test/java/com/pickpick/slackevent/SlackEventTest.java
  backend/src/test/java/com/pickpick/slackevent/application/channel/ChannelDeletedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/channel/ChannelRenameServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/member/MemberChangedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/member/MemberJoinServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageChangedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageCreatedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageDeletedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageFileShareServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastServiceTest.java
  backend/src/test/java/com/pickpick/utils/JsonUtilsTest.java
  backend/src/test/java/utils/JsonUtils.java
Labels: 🎉 BE, ⚙️ REFACTOR

#518 fix: 사파리에서 로그인 되지 않는 버그 해결
  frontend/src/@utils/index.ts
Labels: 🎁 FE, 🛠 FIX

#519 fix: 달력 컴포넌트 미래 날짜 및 빈 공간 클릭시 데이터 요청되는 버그 수정
  frontend/src/components/Calendar/index.tsx
  frontend/src/components/Calendar/style.ts
  frontend/src/hooks/useCalendar.ts
Labels: 🎁 FE, 🛠 FIX

#521 refactor: reminderModal component 리팩터링
  frontend/src/@constants/index.ts
  frontend/src/components/DatePicker/index.tsx
  frontend/src/components/DatePicker/style.ts
  frontend/src/components/DateTimePickerOptions/style.ts
  frontend/src/components/Dropdown/index.tsx
  frontend/src/components/ReminderModal/index.tsx
  frontend/src/components/ReminderModal/style.ts
  frontend/src/components/TimePicker/index.tsx
  frontend/src/hooks/useDatePicker.ts
  frontend/src/hooks/useSetReminder.ts
  frontend/src/hooks/useTimePicker.ts
Labels: 🎁 FE, ⚙️ REFACTOR

#527 refactor: 최상단으로 스크롤을 움직이는 로직 리팩터링
  frontend/src/hooks/useScrollToTop.ts
  frontend/src/pages/Bookmark/index.tsx
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/Reminder/index.tsx
  frontend/src/pages/SpecificDateFeed/index.tsx
Labels: 🎁 FE, ⚙️ REFACTOR

#531 refactor: 쿼리에서 불필요한 left outer join 삭제
  backend/src/main/java/com/pickpick/channel/application/ChannelSubscriptionService.java
  backend/src/main/java/com/pickpick/channel/domain/ChannelSubscriptionRepository.java
  backend/src/main/java/com/pickpick/message/domain/BookmarkRepository.java
  backend/src/main/java/com/pickpick/message/domain/ReminderRepository.java
Labels: 🎉 BE, ⚙️ REFACTOR

#529 fix: Drawer 내부 클릭 시, Drawer 가 닫히는 문제 해결
  frontend/src/components/@layouts/Navigation/index.tsx
  frontend/src/components/Dropdown/index.tsx
  frontend/src/hooks/useOuterClick.ts
Labels: 🎁 FE, 🛠 FIX

#538 hotfix: layout footer 제거
  frontend/src/components/@layouts/Footer/index.tsx
  frontend/src/components/@layouts/Footer/style.ts
  frontend/src/components/@layouts/LayoutContainer/index.tsx
Labels: 🎁 FE, 🚨 HOTFIX

#539 hotfix: remove import 문 제거
  frontend/src/pages/UnexpectedError/index.tsx
Labels: ✨ FEAT, 🚨 HOTFIX

#540 hotfix: channel event의 request 형식 변경
  backend/src/main/java/com/pickpick/slackevent/application/channel/ChannelDeletedService.java
  backend/src/main/java/com/pickpick/slackevent/application/channel/dto/ChannelDeletedEventDto.java
  backend/src/main/java/com/pickpick/slackevent/application/channel/dto/ChannelDeletedRequest.java
  backend/src/main/java/com/pickpick/slackevent/application/channel/dto/ChannelEventDto.java
  backend/src/main/java/com/pickpick/slackevent/application/channel/dto/ChannelRenameRequest.java
  backend/src/test/java/com/pickpick/slackevent/application/channel/ChannelDeletedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/channel/ChannelRenameServiceTest.java
Labels: 🐛 BUG, 🎉 BE, 🚨 HOTFIX

#541 hotfix: UI 버그 수정
  frontend/src/components/@layouts/LayoutContainer/style.ts
Labels: 🎁 FE, 🚨 HOTFIX

#542 main 브랜치와 develop 브랜치 동기화
  backend/src/main/java/com/pickpick/slackevent/application/channel/ChannelDeletedService.java
  backend/src/main/java/com/pickpick/slackevent/application/channel/dto/ChannelRenameRequest.java
  frontend/src/components/@layouts/Footer/index.tsx
Labels: 🌈 ALL

#543 hotfix: 누락된 파일 추가
  backend/src/main/java/com/pickpick/slackevent/application/channel/ChannelDeletedService.java
Labels: 🎉 BE, 🚨 HOTFIX

#550 refactor: 불필요한 코드 제거 및 누락된 절대경로 적용
  frontend/src/@styles/shared.ts
  frontend/src/@styles/theme.ts
  frontend/src/@utils/index.test.ts
  frontend/src/Routes.tsx
  frontend/src/api/auth.ts
  frontend/src/api/bookmarks.ts
  frontend/src/api/channels.ts
  frontend/src/api/messages.ts
  frontend/src/api/reminders.ts
  frontend/src/components/@layouts/Footer/index.tsx
  frontend/src/components/@shared/WrapperLink/index.tsx
  frontend/src/components/Calendar/index.tsx
  frontend/src/components/DateDropdown/index.tsx
  frontend/src/components/DateDropdownMenu/index.tsx
  frontend/src/components/DatePicker/index.tsx
  frontend/src/components/ReminderModal/index.tsx
  frontend/src/components/TimePicker/index.tsx
  frontend/src/hooks/query/useMutateReminder.ts
  frontend/src/hooks/useDatePicker.ts
  frontend/src/hooks/useSnackbar.ts
  frontend/src/hooks/useTimePicker.ts
  frontend/src/index.tsx
  frontend/src/pages/Bookmark/index.tsx
  frontend/src/pages/Reminder/index.tsx
  frontend/src/pages/SearchResult/index.tsx
  frontend/src/pages/SpecificDateFeed/index.tsx
Labels: 🎁 FE, ⚙️ REFACTOR

#551 refactor: 메시지 조회 테스트 효율 개선
  backend/src/test/java/com/pickpick/acceptance/AcceptanceTest.java
  backend/src/test/java/com/pickpick/channel/application/ChannelCreateServiceTest.java
  backend/src/test/java/com/pickpick/channel/application/ChannelServiceTest.java
  backend/src/test/java/com/pickpick/channel/application/ChannelSubscriptionServiceTest.java
  backend/src/test/java/com/pickpick/channel/ui/ChannelControllerTest.java
  backend/src/test/java/com/pickpick/channel/ui/ChannelSubscriptionControllerTest.java
  backend/src/test/java/com/pickpick/message/application/BookmarkServiceTest.java
  backend/src/test/java/com/pickpick/message/application/MessageServiceTest.java
  backend/src/test/java/com/pickpick/message/application/ReminderServiceTest.java
  backend/src/test/java/com/pickpick/message/ui/BookmarkControllerTest.java
  backend/src/test/java/com/pickpick/message/ui/MessageControllerTest.java
  backend/src/test/java/com/pickpick/message/ui/ReminderControllerTest.java
  backend/src/test/java/com/pickpick/slackevent/SlackEventTest.java
  backend/src/test/java/com/pickpick/slackevent/application/channel/ChannelDeletedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/channel/ChannelRenameServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/member/MemberChangedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/member/MemberJoinServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageChangedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageCreatedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageDeletedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageFileShareServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageThreadBroadcastServiceTest.java
  backend/src/test/java/com/pickpick/support/DatabaseCleaner.java
  backend/src/test/java/com/pickpick/support/JsonUtils.java
  backend/src/test/java/com/pickpick/support/RestDocsConfiguration.java
  backend/src/test/java/com/pickpick/support/RestDocsTestSupport.java
Labels: 🎉 BE, ⚙️ REFACTOR, 💯 TEST

#553 refactor: 리마인드 메시지 뷰 개선
  backend/src/main/java/com/pickpick/message/application/ReminderSender.java
Labels: 🎉 BE, ⚙️ REFACTOR
