Repository woowacourse-teams/2022-pickpick, pull requests merged in 2022-07, with the labels that each got.

#20 chore: 필요한 Assets 파일 추가
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/public/assets/fonts/Roboto-Bold.woff
  frontend/public/assets/fonts/Roboto-BoldItalic.woff
  frontend/public/assets/fonts/Roboto-Italic.woff
  frontend/public/assets/fonts/Roboto-Light.woff
  frontend/public/assets/fonts/Roboto-LightItalic.woff
  frontend/public/assets/fonts/Roboto-Regular.woff
  frontend/public/assets/fonts/Twayair.woff
  frontend/public/assets/icons/AlarmIcon-Active.svg
  frontend/public/assets/icons/AlarmIcon-Unactive.svg
  frontend/public/assets/icons/ArrowIcon-Down.svg
  frontend/public/assets/icons/ArrowIcon-Left.svg
  frontend/public/assets/icons/ArrowIcon-Right.svg
  frontend/public/assets/icons/HomeIcon-Fill.svg
  frontend/public/assets/icons/HomeIcon-Unfill.svg
  frontend/public/assets/icons/InfoIcon.svg
  frontend/public/assets/icons/MenuIcon.svg
  frontend/public/assets/icons/RemoveIcon.svg
  frontend/public/assets/icons/SearchIcon.svg
  frontend/public/assets/icons/StarIcon-Fill.svg
  frontend/public/assets/icons/StarIcon-Unfill.svg
  frontend/src/@types/custom.d.ts
  frontend/src/App.tsx
  frontend/src/GlobalStyle.ts
  frontend/tsconfig.json
  frontend/webpack.config.js
Labels: 🎁 FE

#21 chore: 웹팩 설정 파일 Mode 분리
  frontend/package-lock.json
  frontend/package.json
  frontend/webpack.common.js
  frontend/webpack.dev.js
  frontend/webpack.prod.js
Labels: 🎁 FE

#24 feat: 글로벌 스타일 설정
  frontend/src/@styles/GlobalStyle.ts
  frontend/src/@styles/colors.ts
  frontend/src/@styles/fontSize.ts
  frontend/src/@styles/theme.ts
  frontend/src/index.tsx
Labels: 🎁 FE

#25 feat: 전체 레이아웃 설정
  frontend/.eslintrc.json
  frontend/public/assets/icons/GithubIcon.svg
  frontend/public/assets/icons/YoutubeIcon.svg
  frontend/public/index.html
  frontend/src/@styles/GlobalStyle.ts
  frontend/src/@types/shared.ts
  frontend/src/App.tsx
  frontend/src/components/Layout/Footer/index.tsx
  frontend/src/components/Layout/Footer/style.ts
  frontend/src/components/Layout/Header/index.tsx
  frontend/src/components/Layout/Header/style.ts
  frontend/src/components/Layout/LayoutContainer/index.tsx
  frontend/src/components/Layout/LayoutContainer/style.ts
  frontend/src/components/Layout/Navigation/index.tsx
  frontend/src/components/Layout/Navigation/style.ts
  frontend/src/index.tsx
  frontend/src/pages/Home.tsx
  frontend/tsconfig.json
  frontend/webpack.common.js
Labels: 🎁 FE

#26 chore: global .gitignore 파일 추가
  .gitignore
Labels: 🌈 ALL

#29 feat: 실시간 메시지 저장
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/pickpick/controller/EventController.java
  backend/src/main/java/com/pickpick/controller/dto/MessageDto.java
  backend/src/main/java/com/pickpick/entity/Message.java
  backend/src/main/java/com/pickpick/entity/User.java
  backend/src/main/java/com/pickpick/exception/UserNotFoundException.java
  backend/src/main/java/com/pickpick/repository/MessageRepository.java
  backend/src/main/java/com/pickpick/repository/UserRepository.java
  backend/src/main/java/com/pickpick/service/MessageService.java
  backend/src/main/java/com/pickpick/utils/TimeUtils.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/pickpick/acceptance/AcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/EventAcceptanceTest.java
  backend/src/test/java/com/pickpick/utils/TimeUtilsTest.java
Labels: 🎉 BE

#31 feat: @shared component 생성 및 Home page UI 작성
  frontend/.storybook/main.js
  frontend/.storybook/preview.js
  frontend/public/assets/icons/AlarmIcon-Inactive.svg
  frontend/public/assets/icons/GithubIcon.svg
  frontend/public/assets/icons/YoutubeIcon.svg
  frontend/public/assets/images/MockImage.png
  frontend/public/index.html
  frontend/src/@styles/GlobalStyle.ts
  frontend/src/@styles/fontSize.ts
  frontend/src/@styles/shared.ts
  frontend/src/@styles/theme.ts
  frontend/src/@types/custom.d.ts
  frontend/src/@utils/utils.ts
  frontend/src/components/@shared/Button/index.stories.js
  frontend/src/components/@shared/Button/index.tsx
  frontend/src/components/@shared/Button/style.ts
  frontend/src/components/@shared/Dimmer/index.tsx
  frontend/src/components/@shared/Dimmer/style.ts
  frontend/src/components/@shared/WrapperButton/index.stories.js
  frontend/src/components/@shared/WrapperButton/index.tsx
  frontend/src/components/@shared/WrapperButton/style.ts
  frontend/src/components/Dropdown/index.stories.js
  frontend/src/components/Dropdown/index.tsx
  frontend/src/components/Dropdown/style.ts
  frontend/src/components/DropdownMenu/index.stories.js
  frontend/src/components/DropdownMenu/index.tsx
  frontend/src/components/DropdownMenu/style.ts
  frontend/src/components/DropdownToggle/index.stories.js
  frontend/src/components/DropdownToggle/index.tsx
  frontend/src/components/DropdownToggle/style.ts
  frontend/src/components/Layout/Navigation/index.tsx
  frontend/src/components/MessageCard/index.stories.js
  frontend/src/components/MessageCard/index.tsx
  frontend/src/components/MessageCard/style.ts
  frontend/src/components/ProfileImage/index.stories.js
  frontend/src/components/ProfileImage/index.tsx
  frontend/src/components/ProfileImage/style.ts
  frontend/src/components/SearchInput/index.stories.js
  frontend/src/components/SearchInput/index.tsx
  frontend/src/components/SearchInput/style.ts
  frontend/src/components/layouts/Footer/index.tsx
  frontend/src/components/layouts/Footer/style.ts
  frontend/src/components/layouts/Header/index.tsx
  frontend/src/components/layouts/Header/style.ts
  frontend/src/components/layouts/LayoutContainer/index.tsx
  frontend/src/components/layouts/LayoutContainer/style.ts
  frontend/src/components/layouts/Navigation/index.tsx
  frontend/src/components/layouts/Navigation/style.ts
  frontend/src/index.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/Home/index.tsx
  frontend/src/pages/Home/style.ts
  frontend/tsconfig.json
Labels: 🎁 FE

#41 feat: Home Page MSW 모킹
  frontend/package-lock.json
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/@utils/index.ts
  frontend/src/components/MessageCard/index.tsx
  frontend/src/index.tsx
  frontend/src/mocks/browser.ts
  frontend/src/mocks/data/index.ts
  frontend/src/mocks/handlers.ts
  frontend/src/pages/Home/index.tsx
Labels: 🎁 FE

#42 refactor: Slack event URL 분기처리 개선
  backend/src/main/java/com/pickpick/controller/EventController.java
  backend/src/main/java/com/pickpick/controller/event/SlackEvent.java
  backend/src/main/java/com/pickpick/exception/SlackEventNotFoundException.java
  backend/src/main/java/com/pickpick/service/MessageCreatedService.java
  backend/src/main/java/com/pickpick/service/MessageService.java
  backend/src/main/java/com/pickpick/service/SlackEventService.java
  backend/src/main/java/com/pickpick/service/SlackEventServiceFinder.java
  backend/src/main/java/com/pickpick/utils/TimeUtils.java
  backend/src/test/java/com/pickpick/acceptance/EventAcceptanceTest.java
  backend/src/test/java/com/pickpick/controller/event/SlackEventTest.java
Labels: 🎉 BE

#44 refactor: React-Query 적용하여 API 연동
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/messages.ts
  frontend/src/index.tsx
  frontend/src/pages/Home/index.tsx
Labels: 🎁 FE

#49 fix: Dropdown z-index 수정
  frontend/src/@styles/colors.ts
  frontend/src/@styles/theme.ts
  frontend/src/components/layouts/LayoutContainer/index.tsx
  frontend/src/components/layouts/LayoutContainer/style.ts
  frontend/src/components/layouts/Navigation/style.ts
  frontend/src/pages/Home/style.ts
Labels: 🐛 버그, 🎁 FE

#50 fix: Card Toggle 기능제거
  frontend/src/@utils/index.ts
  frontend/src/components/MessageCard/index.tsx
  frontend/src/components/MessageCard/style.ts
  frontend/src/mocks/data/index.ts
Labels: 🐛 버그, 🎁 FE

#51 fix: 유저 프로필 이미지 border-radius 추가
  frontend/src/components/ProfileImage/style.ts
Labels: 🐛 버그, 🎁 FE

#52 fix: 서버에서 받아온 메시지 작성일 가공
  frontend/src/@utils/index.ts
  frontend/src/components/MessageCard/index.tsx
Labels: 🐛 버그, 🎁 FE

#53 fix: MessageCard component UI 반응형 구현
  frontend/src/components/MessageCard/index.tsx
  frontend/src/components/MessageCard/style.ts
  frontend/src/components/SearchInput/style.ts
  frontend/src/pages/Home/index.tsx
  frontend/src/pages/Home/style.ts
Labels: 🐛 버그, 🎁 FE

#61 feat: Skeleton Component 작성 및 적용
  frontend/src/components/MessageCardSkeleton/index.stories.js
  frontend/src/components/MessageCardSkeleton/index.tsx
  frontend/src/components/MessageCardSkeleton/style.ts
  frontend/src/pages/Home/index.tsx
Labels: 🎁 FE, ✨ FEAT

#63 refactor: API fetch Axios 적용
  frontend/package-lock.json
  frontend/package.json
  frontend/src/@types/shared.ts
  frontend/src/api/index.ts
  frontend/src/api/messages.ts
  frontend/src/pages/Home/index.tsx
Labels: 🎁 FE, ⚙️ REFACTOR

#64 feat: 무한 스크롤 구현
  frontend/src/@types/shared.ts
  frontend/src/api/messages.ts
  frontend/src/components/@shared/InfiniteScroll/index.tsx
  frontend/src/mocks/data/index.ts
  frontend/src/mocks/handlers.ts
  frontend/src/pages/Home/index.tsx
Labels: 🎁 FE, ✨ FEAT

#66 docs: 이슈, PR 템플릿 수정
  .github/ISSUE_TEMPLATE/DEFAULT_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE/DEFAULT_TEMPLATE.md
  .github/pull_reqeust_template.md
Labels: 🌈 ALL, 📝 DOCS

#67 docs: 리뷰어 자동 할당 github action 추가
  .github/reviewers.yml
  .github/workflows/auto_request_review.yml
Labels: 🌈 ALL, 📝 DOCS

#70 refactor: MessageCardSkeleton UI 수정
  frontend/src/components/MessageCardSkeleton/index.tsx
  frontend/src/components/MessageCardSkeleton/style.ts
Labels: 🎁 FE, ⚙️ REFACTOR

#73 refactor: useInfiniteQuery에서 반환되는 Messages 가공 함수 수정
  frontend/src/pages/Home/index.tsx
Labels: 🎁 FE, ⚙️ REFACTOR

#74 feature: 스타트 페이지 UI 구현
  frontend/src/@styles/GlobalStyle.ts
  frontend/src/@styles/colors.ts
  frontend/src/@styles/theme.ts
  frontend/src/components/layouts/LayoutContainer/index.tsx
  frontend/src/components/layouts/LayoutContainer/style.ts
  frontend/src/index.tsx
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/Feed/style.ts
  frontend/src/pages/Home/index.tsx
  frontend/src/pages/Home/style.ts
Labels: 🎁 FE, ✨ FEAT

#76 feat: 채널 선택 page UI 구현
  frontend/src/@styles/GlobalStyle.ts
  frontend/src/components/layouts/LayoutContainer/index.tsx
  frontend/src/index.tsx
  frontend/src/pages/AddChannel/index.tsx
  frontend/src/pages/AddChannel/style.ts
Labels: 🎁 FE, ✨ FEAT

#77 feat: 어플리케이션 구동 시 워크스페이스의 유저 저장
  backend/build.gradle
  backend/src/main/java/com/pickpick/controller/EventController.java
  backend/src/main/java/com/pickpick/controller/dto/MessageDto.java
  backend/src/main/java/com/pickpick/entity/Member.java
  backend/src/main/java/com/pickpick/entity/Message.java
  backend/src/main/java/com/pickpick/exception/MemberNotFoundException.java
  backend/src/main/java/com/pickpick/repository/MemberRepository.java
  backend/src/main/java/com/pickpick/repository/UserRepository.java
  backend/src/main/java/com/pickpick/service/MemberInitializer.java
  backend/src/main/java/com/pickpick/service/MessageCreatedService.java
  backend/src/test/java/com/pickpick/acceptance/AcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/MemberAcceptanceTest.java
  backend/src/test/resources/application-test.yml
Labels: 🎉 BE, ✨ FEAT

#84 feat: 채널 선택 Drawer UI 구현
  frontend/public/assets/icons/PlusIcon.svg
  frontend/public/index.html
  frontend/src/@styles/theme.ts
  frontend/src/components/@shared/Portal/index.tsx
  frontend/src/components/Drawer/index.stories.js
  frontend/src/components/Drawer/index.tsx
  frontend/src/components/Drawer/style.ts
  frontend/src/components/layouts/Navigation/index.tsx
  frontend/src/components/layouts/Navigation/style.ts
Labels: 🎁 FE, ✨ FEAT

#83 fix: application-test.yml 파일 제거
  backend/src/test/java/com/pickpick/acceptance/AcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/MemberAcceptanceTest.java
  backend/src/test/resources/application-test.yml
Labels: 🎉 BE, 🛠 FIX

#81 feat: 메시지 조회 API 구현
  backend/build.gradle
  backend/src/main/java/com/pickpick/controller/MessageController.java
  backend/src/main/java/com/pickpick/controller/dto/MessageDto.java
  backend/src/main/java/com/pickpick/controller/dto/SlackMessageRequest.java
  backend/src/main/java/com/pickpick/controller/dto/SlackMessageResponse.java
  backend/src/main/java/com/pickpick/controller/dto/SlackMessageResponses.java
  backend/src/main/java/com/pickpick/entity/Channel.java
  backend/src/main/java/com/pickpick/entity/Message.java
  backend/src/main/java/com/pickpick/exception/MessageNotFoundException.java
  backend/src/main/java/com/pickpick/exception/WrongMessageRequestException.java
  backend/src/main/java/com/pickpick/repository/MessageRepository.java
  backend/src/main/java/com/pickpick/service/MessageCreatedService.java
  backend/src/main/java/com/pickpick/service/MessageService.java
  backend/src/test/java/com/pickpick/acceptance/EventAcceptanceTest.java
  backend/src/test/java/com/pickpick/service/MessageServiceTest.java
  backend/src/test/resources/message.sql
Labels: 🎉 BE, ✨ FEAT

#89 feat: 각 날짜에 맞는 Message 그룹핑 구현 및 Dropdown Menu Option 구현
  frontend/src/api/messages.ts
  frontend/src/components/@shared/Dimmer/style.ts
  frontend/src/components/Drawer/style.ts
  frontend/src/components/Dropdown/index.tsx
  frontend/src/components/DropdownMenu/index.tsx
  frontend/src/index.tsx
  frontend/src/mocks/data/index.ts
  frontend/src/mocks/handlers.ts
  frontend/src/pages/Feed/index.tsx
Labels: 🎁 FE, ✨ FEAT

#92 MSW API 모킹
  frontend/src/mocks/data/index.ts
  frontend/src/mocks/handlers.ts
Labels: 🎁 FE, ✨ FEAT

#94 fix: MSW API 모킹 수정
  frontend/src/api/messages.ts
  frontend/src/mocks/data/index.ts
  frontend/src/mocks/handlers.ts
  frontend/webpack.common.js
Labels: 🎁 FE, 🛠 FIX

#86 feat: 채널 목록 조회
  backend/src/main/java/com/pickpick/controller/ChannelController.java
  backend/src/main/java/com/pickpick/controller/dto/ChannelResponse.java
  backend/src/main/java/com/pickpick/controller/dto/ChannelResponses.java
  backend/src/main/java/com/pickpick/entity/Channel.java
  backend/src/main/java/com/pickpick/entity/ChannelSubscription.java
  backend/src/main/java/com/pickpick/repository/ChannelRepository.java
  backend/src/main/java/com/pickpick/repository/ChannelSubscriptionRepository.java
  backend/src/main/java/com/pickpick/repository/MemberRepository.java
  backend/src/main/java/com/pickpick/service/ChannelService.java
  backend/src/main/java/com/pickpick/service/ChannelSubscriptionService.java
  backend/src/main/java/com/pickpick/utils/AuthorizationExtractor.java
  backend/src/test/java/com/pickpick/acceptance/AcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/ChannelAcceptanceTest.java
  backend/src/test/java/com/pickpick/service/ChannelSubscriptionServiceTest.java
Labels: 🎉 BE, ✨ FEAT

#95 feat: 채널 구독 및 api 추가를 main에 반영
  backend/src/main/java/com/pickpick/controller/ChannelSubscriptionController.java
  backend/src/main/java/com/pickpick/controller/dto/ChannelOrderRequest.java
  backend/src/main/java/com/pickpick/controller/dto/ChannelSubscriptionRequest.java
  backend/src/main/java/com/pickpick/controller/dto/ChannelSubscriptionResponse.java
  backend/src/main/java/com/pickpick/controller/dto/ChannelSubscriptionResponses.java
  backend/src/main/java/com/pickpick/entity/ChannelSubscription.java
  backend/src/main/java/com/pickpick/exception/ChannelNotFoundException.java
  backend/src/main/java/com/pickpick/exception/MemberNotFoundException.java
  backend/src/main/java/com/pickpick/exception/SlackEventNotFoundException.java
  backend/src/main/java/com/pickpick/repository/ChannelRepository.java
  backend/src/main/java/com/pickpick/repository/ChannelSubscriptionRepository.java
  backend/src/main/java/com/pickpick/repository/MemberRepository.java
  backend/src/main/java/com/pickpick/service/ChannelSubscriptionService.java
Labels: 🎉 BE, ✨ FEAT

#100 feat: Dropdown Menu 옵션 날짜 클릭 시, 해당 날짜 검색 페이지 라우팅 구현
  frontend/src/api/messages.ts
  frontend/src/components/@shared/NextInfiniteScroll/index.tsx
  frontend/src/components/DropdownMenu/index.tsx
  frontend/src/hooks/useIntersectionObserver.ts
  frontend/src/index.tsx
  frontend/src/mocks/data/index.ts
  frontend/src/mocks/handlers.ts
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/SpecificDateFeed/index.tsx
Labels: 🎁 FE, ✨ FEAT

#103 feat: Navigation 페이지 라우팅 구현
  frontend/src/@constants/index.ts
  frontend/src/App.tsx
  frontend/src/Routes.tsx
  frontend/src/components/@shared/WrapperButton/style.ts
  frontend/src/components/@shared/WrapperLink/index.tsx
  frontend/src/components/@shared/WrapperLink/style.ts
  frontend/src/components/layouts/LayoutContainer/index.tsx
  frontend/src/components/layouts/Navigation/index.tsx
  frontend/src/index.tsx
  frontend/src/pages/Alarm/index.tsx
  frontend/src/pages/Bookmark/index.tsx
  frontend/src/pages/NotFound/index.tsx
Labels: 🎁 FE, ✨ FEAT

#106 fix: 메시지 조회 API 오류 수정.
  backend/src/main/java/com/pickpick/service/MessageService.java
Labels: 🐛 BUG, 🎉 BE

#108 refactor: 메시지 저장 API 개선
  backend/src/main/java/com/pickpick/controller/MessageController.java
  backend/src/main/java/com/pickpick/controller/dto/MessageDto.java
  backend/src/main/java/com/pickpick/controller/dto/SlackMessageRequest.java
  backend/src/main/java/com/pickpick/controller/dto/SlackMessageResponses.java
  backend/src/main/java/com/pickpick/entity/Message.java
  backend/src/main/java/com/pickpick/exception/WrongMessageRequestException.java
  backend/src/main/java/com/pickpick/repository/ChannelRepository.java
  backend/src/main/java/com/pickpick/service/MessageChangedService.java
  backend/src/main/java/com/pickpick/service/MessageCreatedService.java
  backend/src/main/java/com/pickpick/service/MessageService.java
  backend/src/test/java/com/pickpick/acceptance/EventAcceptanceTest.java
  backend/src/test/java/com/pickpick/service/MessageChangedServiceTest.java
  backend/src/test/java/com/pickpick/service/MessageDeletedServiceTest.java
  backend/src/test/java/com/pickpick/service/MessageServiceTest.java
  backend/src/test/resources/message.sql
Labels: 🐛 BUG, 🎉 BE, ✨ FEAT

#111 chore: API Endpoint 개발모드/배포모드 구분
  frontend/.env.development
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/index.ts
  frontend/webpack.common.js
  frontend/webpack.dev.js
  frontend/webpack.prod.js
Labels: 🎁 FE, 🧹 CHORE

#112 refactor: MessageCard UI 수정
  frontend/src/@styles/colors.ts
  frontend/src/@styles/theme.ts
  frontend/src/components/@shared/IconButton/index.stories.js
  frontend/src/components/@shared/IconButton/index.tsx
  frontend/src/components/@shared/IconButton/style.ts
  frontend/src/components/MessageCard/index.tsx
  frontend/src/components/MessageCard/style.ts
Labels: 🎁 FE, ⚙️ REFACTOR

#118 refactor: 스크롤 이벤트 unmount시 제거
  frontend/src/pages/SpecificDateFeed/index.tsx
Labels: 🎁 FE, ⚙️ REFACTOR

#110 test: 채널과 채널 구독 인수테스트 추가
  backend/src/test/java/com/pickpick/acceptance/AcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/ChannelAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/ChannelSubscriptionAcceptanceTest.java
  backend/src/test/resources/channel.sql
  backend/src/test/resources/truncate.sql
Labels: 🎉 BE, 💯 TEST

#116 fix: CORS 대응
  backend/src/main/java/com/pickpick/config/CorsConfig.java
Labels: 🐛 BUG, 🎉 BE, ✨ FEAT

#123 hotfix: 메시지 조회 API 응답 관련 오류 수정
  backend/src/main/java/com/pickpick/service/MessageService.java
Labels: 🐛 BUG, 🎉 BE

#127 fix: z-index 수정
  frontend/src/components/@shared/Dimmer/style.ts
  frontend/src/components/Drawer/style.ts
  frontend/src/components/Dropdown/style.ts
  frontend/src/components/layouts/Navigation/style.ts
Labels: 🎁 FE, 🛠 FIX

#130 feat: 줍줍 로고 추가
  frontend/public/assets/icons/pickpick.svg
  frontend/src/pages/Home/index.tsx
  frontend/src/pages/Home/style.ts
Labels: 🎁 FE, ✨ FEAT

#133 refactor: Navigation component 높이 수정
  frontend/src/components/Drawer/style.ts
  frontend/src/components/layouts/Navigation/style.ts
Labels: 🎁 FE, ⚙️ REFACTOR

#138 hotfix: tsconfig 수정
  frontend/tsconfig.json
Labels: 🎁 FE, 🚨 HOTFIX

#129 feat: 구독 관련 중복 요청 시 예외처리 추가
  backend/src/main/java/com/pickpick/controller/ControllerAdvice.java
  backend/src/main/java/com/pickpick/controller/dto/ChannelOrderRequest.java
  backend/src/main/java/com/pickpick/exception/SubscriptionDuplicatedException.java
  backend/src/main/java/com/pickpick/exception/SubscriptionNotExistException.java
  backend/src/main/java/com/pickpick/repository/ChannelSubscriptionRepository.java
  backend/src/main/java/com/pickpick/service/ChannelSubscriptionService.java
  backend/src/test/java/com/pickpick/acceptance/ChannelAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/ChannelSubscriptionAcceptanceTest.java
Labels: 🎉 BE, ✨ FEAT

#137 feat: 메시지 조회 API 인수 테스트 추가
  backend/src/main/java/com/pickpick/controller/dto/SlackMessageRequest.java
  backend/src/main/java/com/pickpick/controller/dto/SlackMessageResponse.java
  backend/src/main/java/com/pickpick/controller/dto/SlackMessageResponses.java
  backend/src/test/java/com/pickpick/acceptance/AcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/MessageAcceptanceTest.java
  backend/src/test/java/com/pickpick/service/MessageServiceTest.java
  backend/src/test/resources/message.sql
Labels: 🐛 BUG, 🎉 BE, 💯 TEST

#141 chore: 웹팩 설정 수정
  frontend/webpack.common.js
  frontend/webpack.dev.js
Labels: 🎁 FE, 🚨 HOTFIX

#142 feat: 모바일에서 onWheel 이벤트를 touch 이벤트로 대체
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/SpecificDateFeed/index.tsx
Labels: 🎁 FE, ✨ FEAT

#143 feat: 라우팅 상태에 따라 Navigation 아이콘 focus 상태 수정
  frontend/src/components/layouts/Navigation/index.tsx
  frontend/src/pages/AddChannel/index.tsx
  frontend/src/pages/Home/index.tsx
Labels: 🎁 FE, ✨ FEAT

#145 style: MessageCard UI 변경
  frontend/src/components/MessageCard/index.tsx
Labels: 🎁 FE, 💄 STYLE

#146 refactor: Exception 관련 처리
  backend/src/main/java/com/pickpick/controller/ControllerAdvice.java
  backend/src/main/java/com/pickpick/controller/event/SlackEvent.java
  backend/src/main/java/com/pickpick/exception/BadRequestException.java
  backend/src/main/java/com/pickpick/exception/ChannelNotFoundException.java
  backend/src/main/java/com/pickpick/exception/MemberNotFoundException.java
  backend/src/main/java/com/pickpick/exception/MessageNotFoundException.java
  backend/src/main/java/com/pickpick/exception/NotFoundException.java
  backend/src/main/java/com/pickpick/exception/SlackEventNotFoundException.java
  backend/src/main/java/com/pickpick/exception/SlackEventServiceNotFoundException.java
  backend/src/main/java/com/pickpick/exception/SubscriptionDuplicatedException.java
  backend/src/main/java/com/pickpick/exception/SubscriptionNotExistException.java
  backend/src/main/java/com/pickpick/service/ChannelSubscriptionService.java
  backend/src/main/java/com/pickpick/service/MessageCreatedService.java
  backend/src/main/java/com/pickpick/service/MessageService.java
  backend/src/main/java/com/pickpick/service/SlackEventServiceFinder.java
Labels: 🎉 BE, ⚙️ REFACTOR

#149 fix: 무한 스크롤 관련 버그 수정
  frontend/src/pages/SpecificDateFeed/index.tsx
Labels: 🎁 FE, 🛠 FIX

#153 feat: 채널 추가 페이지 채널 목록 API 연동
  frontend/src/@types/shared.ts
  frontend/src/api/channels.ts
  frontend/src/components/Drawer/index.tsx
  frontend/src/components/layouts/Navigation/index.tsx
  frontend/src/pages/AddChannel/index.tsx
Labels: 🎁 FE, ✨ FEAT

#155 style: Jenkinsfile 스타일 개선
  backend/Jenkinsfile
Labels: 🎉 BE, 💄 STYLE

#152 test: 채널 구독에 대한 서비스 테스트 추가
  backend/src/main/java/com/pickpick/exception/SubscriptionDuplicateException.java
  backend/src/main/java/com/pickpick/service/ChannelSubscriptionService.java
  backend/src/test/java/com/pickpick/controller/event/SlackEventTest.java
  backend/src/test/java/com/pickpick/service/ChannelSubscriptionServiceTest.java
Labels: 🎉 BE, 💯 TEST

#158 refactor: 메시지 조회 API 동적 쿼리 생성 로직 리팩터링
  backend/src/main/java/com/pickpick/config/QuerydslConfig.java
  backend/src/main/java/com/pickpick/service/MessageService.java
  backend/src/test/java/com/pickpick/acceptance/MessageAcceptanceTest.java
Labels: 🎉 BE, ⚙️ REFACTOR

#171 fix: 패키지 구조 변경 후 QMessage import 이슈 수정
  backend/src/main/java/com/pickpick/message/application/MessageService.java
Labels: 🎉 BE, 🚨 HOTFIX

#183 refactor: 구독 생성, 삭제 API 스펙 변경
  backend/src/main/java/com/pickpick/channel/application/ChannelSubscriptionService.java
  backend/src/main/java/com/pickpick/channel/ui/ChannelSubscriptionController.java
  backend/src/main/java/com/pickpick/channel/ui/dto/ChannelSubscriptionRequest.java
  backend/src/test/java/com/pickpick/acceptance/ChannelAcceptanceTest.java
Labels: 🎉 BE, ⚙️ REFACTOR

#184 수정된 채널 구독/해제 API 반영
  frontend/src/api/channels.ts
Labels: 🎁 FE, ⚙️ REFACTOR

#188 refactor: 양방향 무한 스크롤 로직 리팩토링 및 Feed Page 리팩토링
  frontend/src/@utils/index.ts
  frontend/src/api/utils.ts
  frontend/src/components/@shared/InfiniteScroll/index.tsx
  frontend/src/components/DateDropdown/index.tsx
  frontend/src/components/DateDropdown/style.ts
  frontend/src/components/MessagesLoadingStatus/index.tsx
  frontend/src/hooks/useIntersectionObserver.ts
  frontend/src/hooks/useMessageDate.ts
  frontend/src/hooks/useTopScreenEventHandlers.ts
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/Feed/style.ts
  frontend/src/pages/SpecificDateFeed/index.tsx
Labels: 🎁 FE, ⚙️ REFACTOR

#190 refactor: react-query queryKey 상수화
  frontend/src/@constants/index.ts
  frontend/src/pages/AddChannel/index.tsx
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/SpecificDateFeed/index.tsx
Labels: 🎁 FE, ⚙️ REFACTOR

#192 refactor: url pathname 케밥케이스 적용
  frontend/src/@constants/index.ts
Labels: 🎁 FE, ⚙️ REFACTOR

#172 refactor: 메시지 조회 API 네이밍 관련 추가 리팩터링
  backend/src/main/java/com/pickpick/message/application/MessageService.java
Labels: 🎉 BE, ⚙️ REFACTOR

#174 chore: Spring REST Docs 적용
  backend/build.gradle
  backend/src/docs/asciidoc/api.adoc
  backend/src/test/java/com/pickpick/controller/ChannelControllerTest.java
  backend/src/test/java/com/pickpick/controller/ChannelSubscriptionControllerTest.java
  backend/src/test/java/com/pickpick/controller/MessageControllerTest.java
  backend/src/test/java/com/pickpick/controller/RestDocsConfiguration.java
  backend/src/test/java/com/pickpick/controller/RestDocsTestSupport.java
  backend/src/test/resources/channel-subscription.sql
  backend/src/test/resources/channel.sql
Labels: 🎉 BE, 📝 DOCS

#194 fix: Merge 과정에서의 import issue 및 테스트 코드 깨짐 문제해결
  backend/src/test/java/com/pickpick/controller/ChannelSubscriptionControllerTest.java
Labels: 🎉 BE, 🚨 HOTFIX

#178 refactor: 검색어로 메시지 조회시 대소문자 무시하도록 개선, 테스트 픽스처 수정
  backend/src/main/java/com/pickpick/message/application/MessageService.java
  backend/src/test/java/com/pickpick/acceptance/MessageAcceptanceTest.java
Labels: 🎉 BE, ⚙️ REFACTOR, 💯 TEST, 🚨 HOTFIX

#196 fix: TimeZone UTC+9 설정
  backend/src/main/java/com/pickpick/config/TimeZoneConfig.java
Labels: 🎉 BE, 🚨 HOTFIX

#197 test: 메시지 조회 API 인수테스트 한글 검색 케이스 추가
  backend/src/test/java/com/pickpick/acceptance/MessageAcceptanceTest.java
  backend/src/test/resources/message.sql
Labels: 🎉 BE, 💯 TEST

#198 feat: 구독 중인 채널 Drawer에 보여주는 기능
  frontend/src/@constants/index.ts
  frontend/src/@types/shared.ts
  frontend/src/api/channels.ts
  frontend/src/api/messages.ts
  frontend/src/components/Drawer/index.tsx
  frontend/src/components/layouts/Navigation/index.tsx
  frontend/src/index.tsx
  frontend/src/mocks/handlers.ts
Labels: 🎁 FE, ✨ FEAT

#202 refactor: WrapperLink component에 Link tag NavLink tag로 변경
  frontend/src/Routes.tsx
  frontend/src/components/@layouts/Footer/index.tsx
  frontend/src/components/@layouts/Footer/style.ts
  frontend/src/components/@layouts/Header/index.tsx
  frontend/src/components/@layouts/Header/style.ts
  frontend/src/components/@layouts/LayoutContainer/index.tsx
  frontend/src/components/@layouts/LayoutContainer/style.ts
  frontend/src/components/@layouts/Navigation/index.tsx
  frontend/src/components/@layouts/Navigation/style.ts
  frontend/src/components/@shared/WrapperLink/index.tsx
  frontend/src/components/@shared/WrapperLink/style.ts
  frontend/src/components/Drawer/index.tsx
  frontend/src/pages/AddChannel/index.tsx
Labels: 🎁 FE, ⚙️ REFACTOR

#203 hotfix: 채널 목록 조회 API Endpoint 수정
  frontend/src/@constants/index.ts
  frontend/src/api/channels.ts
  frontend/src/components/@layouts/Navigation/index.tsx
  frontend/src/pages/AddChannel/index.tsx
Labels: 🎁 FE, 🚨 HOTFIX

#180 feat: Github Actions를 이용한 Backend CI 테스트 자동화
  .github/workflows/backend-build-test.yml
Labels: 🎉 BE, 🏗 INFRA

#187 feat: 채널명 변경 이벤트 및 채널 삭제 이벤트 적용
  backend/src/main/java/com/pickpick/channel/application/ChannelSubscriptionService.java
  backend/src/main/java/com/pickpick/channel/domain/Channel.java
  backend/src/main/java/com/pickpick/channel/domain/ChannelRepository.java
  backend/src/main/java/com/pickpick/channel/ui/ChannelSubscriptionController.java
  backend/src/main/java/com/pickpick/exception/SlackBadRequestException.java
  backend/src/main/java/com/pickpick/member/application/MemberInitializer.java
  backend/src/main/java/com/pickpick/message/domain/MessageRepository.java
  backend/src/main/java/com/pickpick/slackevent/application/SlackEvent.java
  backend/src/main/java/com/pickpick/slackevent/application/channel/ChannelDeletedService.java
  backend/src/main/java/com/pickpick/slackevent/application/channel/ChannelRenameService.java
  backend/src/main/java/com/pickpick/slackevent/application/channel/dto/SlackChannelRenameDto.java
  backend/src/main/java/com/pickpick/utils/AuthorizationExtractor.java
  backend/src/test/java/com/pickpick/PickpickApplicationTests.java
  backend/src/test/java/com/pickpick/acceptance/ChannelAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/EventAcceptanceTest.java
  backend/src/test/java/com/pickpick/acceptance/MessageAcceptanceTest.java
  backend/src/test/java/com/pickpick/channel/domain/ChannelTest.java
  backend/src/test/java/com/pickpick/message/MessageServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/SlackEventTest.java
  backend/src/test/java/com/pickpick/slackevent/application/channel/ChannelDeletedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/channel/ChannelRenameServiceTest.java
  backend/src/test/resources/channel.sql
Labels: 🎉 BE, ✨ FEAT

#205 hotfix: ChannelDeletedServiceTest 테스트 격리 처리
  backend/src/test/java/com/pickpick/controller/ChannelControllerTest.java
  backend/src/test/java/com/pickpick/controller/MessageControllerTest.java
  backend/src/test/java/com/pickpick/controller/RestDocsTestSupport.java
  backend/src/test/java/com/pickpick/slackevent/application/channel/ChannelDeletedServiceTest.java
Labels: 🎉 BE, 🚨 HOTFIX

#208 feat: error boundary 구현
  frontend/src/components/ErrorBoundary/index.tsx
  frontend/src/index.tsx
  frontend/src/pages/UnexpectedError/index.tsx
Labels: 🎁 FE, ✨ FEAT

#209 hotfix: TimeUtils 변환 로직 수정, 백엔드 CI 테스트 스크립트 타임존 설정 추가
  .github/workflows/backend-build-test.yml
  backend/src/main/java/com/pickpick/utils/TimeUtils.java
Labels: 🎉 BE, 🚨 HOTFIX

#200 feat: 채널 동적 생성 구현
  backend/src/main/java/com/pickpick/config/SlackConfig.java
  backend/src/main/java/com/pickpick/exception/SlackClientException.java
  backend/src/main/java/com/pickpick/slackevent/application/message/MessageCreatedService.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageChangedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageCreatedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/application/message/MessageDeletedServiceTest.java
Labels: 🎉 BE, ✨ FEAT

#213 feat: Slack Event 요청값 로깅
  backend/src/main/java/com/pickpick/slackevent/ui/SlackEventController.java
  backend/src/main/resources/appenders/async-console-appender.xml
  backend/src/main/resources/appenders/async-file-appender-info.xml
  backend/src/main/resources/logback-spring.xml
Labels: 🎉 BE, ✨ FEAT

#215 feat: 스낵바 컴포넌트 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/@atoms/index.ts
  frontend/src/App.tsx
  frontend/src/components/Snackbar/index.tsx
  frontend/src/components/Snackbar/style.ts
  frontend/src/hooks/useSnackbar.ts
  frontend/src/index.tsx
  frontend/src/pages/Home/index.tsx
Labels: 🎁 FE, ✨ FEAT

#211 feat: 유저 프로필 업데이트 이벤트 발생 시 정보 업데이트
  backend/src/main/java/com/pickpick/exception/MemberInvalidThumbnailUrlException.java
  backend/src/main/java/com/pickpick/exception/MemberInvalidUsernameException.java
  backend/src/main/java/com/pickpick/member/domain/Member.java
  backend/src/main/java/com/pickpick/slackevent/application/SlackEvent.java
  backend/src/main/java/com/pickpick/slackevent/application/member/MemberChangedService.java
  backend/src/main/java/com/pickpick/slackevent/application/member/dto/MemberProfileChangedDto.java
  backend/src/test/java/com/pickpick/acceptance/MemberEventAcceptanceTest.java
  backend/src/test/java/com/pickpick/member/domain/MemberTest.java
  backend/src/test/java/com/pickpick/slackevent/MemberChangedServiceTest.java
  backend/src/test/java/com/pickpick/slackevent/SlackEventTest.java
  backend/src/test/resources/member.sql
Labels: 🎉 BE, ✨ FEAT

#220 feat: suspense를 사용한 loading 상태 구현
  frontend/package-lock.json
  frontend/src/Routes.tsx
  frontend/src/api/channels.ts
  frontend/src/components/Loader/index.tsx
  frontend/src/components/Loader/style.ts
  frontend/src/pages/index.tsx
Labels: 🎁 FE, ✨ FEAT

#230 feat: 북마크 기능 추가
  frontend/src/@constants/index.ts
  frontend/src/@types/shared.ts
  frontend/src/@utils/index.ts
  frontend/src/api/bookmarks.ts
  frontend/src/api/utils.ts
  frontend/src/components/MessageCard/index.tsx
  frontend/src/hooks/useBookmark.ts
  frontend/src/mocks/browser.ts
  frontend/src/mocks/data/channels.ts
  frontend/src/mocks/data/messages.ts
  frontend/src/mocks/handlers/bookmarks.ts
  frontend/src/mocks/handlers/channels.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/messages.ts
  frontend/src/mocks/utils.ts
  frontend/src/pages/Bookmark/index.tsx
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/SpecificDateFeed/index.tsx
Labels: 🎁 FE, ✨ FEAT

#223 style: Unexpected Error component style 추가
  frontend/src/pages/UnexpectedError/index.tsx
  frontend/src/pages/UnexpectedError/style.ts
Labels: 🎁 FE, 💄 STYLE

#235 style: NotFound component style 추가
  frontend/src/pages/NotFound/index.tsx
  frontend/src/pages/NotFound/style.ts
Labels: 🎁 FE, 💄 STYLE

#231 feat: 메시지 조회 시, 빈 문자열을 담은 메시지 필터링
  backend/src/main/java/com/pickpick/message/application/MessageService.java
  backend/src/test/java/com/pickpick/channel/ChannelSubscriptionServiceTest.java
  backend/src/test/java/com/pickpick/message/MessageServiceTest.java
  backend/src/test/resources/message.sql
Labels: 🎉 BE, ✨ FEAT

#238 refactor: 누락된 타입 보강
  frontend/src/@constants/index.ts
  frontend/src/@types/shared.ts
  frontend/src/@utils/index.ts
  frontend/src/api/bookmarks.ts
  frontend/src/api/channels.ts
  frontend/src/api/messages.ts
  frontend/src/api/utils.ts
  frontend/src/components/@layouts/Footer/style.ts
  frontend/src/components/@layouts/Header/style.ts
  frontend/src/components/@layouts/LayoutContainer/index.tsx
  frontend/src/components/@layouts/LayoutContainer/style.ts
  frontend/src/components/@layouts/Navigation/style.ts
  frontend/src/components/@shared/Button/style.ts
  frontend/src/components/@shared/Dimmer/style.ts
  frontend/src/components/@shared/IconButton/style.ts
  frontend/src/components/Drawer/style.ts
  frontend/src/components/DropdownMenu/style.ts
  frontend/src/components/DropdownToggle/style.ts
  frontend/src/components/Loader/style.ts
  frontend/src/components/MessageCard/style.ts
  frontend/src/components/MessageCardSkeleton/style.ts
  frontend/src/components/SearchInput/style.ts
  frontend/src/components/Snackbar/style.ts
  frontend/src/hooks/useBookmark.ts
  frontend/src/hooks/useIntersectionObserver.ts
  frontend/src/hooks/useMessageDate.ts
  frontend/src/hooks/useSnackbar.ts
  frontend/src/hooks/useTopScreenEventHandlers.ts
  frontend/src/pages/Feed/index.tsx
  frontend/src/pages/Home/style.ts
  frontend/src/pages/NotFound/style.ts
  frontend/src/pages/SpecificDateFeed/index.tsx
  frontend/src/pages/UnexpectedError/style.ts
Labels: 🎁 FE, ⚙️ REFACTOR

#239 hotfix: 삭제된 Styled Component 복구
  frontend/src/api/channels.ts
  frontend/src/components/@layouts/LayoutContainer/index.tsx
  frontend/src/components/@layouts/LayoutContainer/style.ts
Labels: 🎁 FE, 🚨 HOTFIX

#240 test: Storybook 누락 파일 추가,정리 및 배포
  frontend/.storybook/preview.js
  frontend/src/components/@shared/IconButton/index.stories.js
  frontend/src/components/@shared/IconButton/index.tsx
  frontend/src/components/@shared/WrapperButton/index.stories.js
  frontend/src/components/DateDropdown/index.stories.js
  frontend/src/components/Drawer/index.stories.js
  frontend/src/components/Dropdown/index.stories.js
  frontend/src/components/DropdownMenu/index.stories.js
  frontend/src/components/DropdownToggle/index.stories.js
  frontend/src/components/Loader/index.stories.js
  frontend/src/components/MessageCard/index.stories.js
  frontend/src/components/MessageCardSkeleton/index.stories.js
  frontend/src/components/ProfileImage/index.stories.js
  frontend/src/components/SearchInput/index.stories.js
Labels: 🎁 FE, 💯 TEST

#229 docs: issue template 및 Rest Docs 문서 수정
  .github/ISSUE_TEMPLATE/feature.md
  backend/src/docs/asciidoc/api.adoc
Labels: 🎉 BE, 🌈 ALL, 📝 DOCS
